### ISSUE TITLE
Servlet dependency error after add browsermob-proxy lib

### ISSUE THREAD

**Issue by shimron** [lightbody/browsermob-proxy#191]
after add browsermob-proxy 2.0 dependency to my pom.xml, when I was trying to start my webapp, I got this error:

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:188)
at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1123)
at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:800)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of org/apache/catalina/loader/WebappClassLoader) previously initiated loading for a different type with name "javax/servlet/ServletContext"
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1191)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1669)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:166)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
... 6 more

**Comment by jekh** [comment]
The easy answer is: try using the latest code from master, declaring a dependency solely on browsermob-core. (If you don't want to use a snapshot version, the good news is that the 2.1.0-beta-1 release is imminent!)

The harder answer is that you seem to have some classloader issues that are going to be tricky to solve, and probably unique to your app server's configuration. If you google for LinkageError, you'll find some good information on it. But hopefully the easy answer works for you!

**Comment by shimron** [comment]
The easy answer doesn't work for me , I can't download the latest snapshot version.

And the harder answer,after google for linkageError, I got some tips.  I added <scope>provide</scope> to the dependency of browsermob-proxy, then the webapp can start successfully. But another exception threw when I was trying to invoke the method the using proxy. Below is the log info:

Servlet.service() for servlet [spring] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: net/lightbody/bmp/proxy/http/ResponseInterceptor] with root cause
java.lang.ClassNotFoundException: net.lightbody.bmp.proxy.http.ResponseInterceptor
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)

**Comment by jekh** [comment]
Using "provided" scope is not a solution to the classloader issue. It simply excludes all of BrowserMob Proxy and its dependencies from your web application. Fixing your classloader issues will require time & research and is beyond the scope of what we can provide here. Alternately, you can build the latest code in master yourself, or you can wait for the 2.1 beta to be released, which should be soon.

Hope that helps! I'm going to close this issue.
