### ISSUE TITLE
UnsupportedClassVersionError - Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by sethuster** [lightbody/browsermob-proxy#236]
Hey guys - I'm getting this error when trying to run BrowserMob:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/lightbody/bmp/proxy/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

I'm running this version of java:
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by sethuster** [comment]
I didn't have my stupid JAVA environment variables set up.  DERP!

**Comment by walmik** [comment]
That was it for me as well, thanks @sethuster & @gkushang for sharing!
`echo export "JAVA_HOME=\$(/usr/libexec/java_home -v 1.8)" >> ~/.profile`

The java version and .profile might change for other users, but ^ that did it for me.

**Comment by rtezera1** [comment]
I'm having the same issue as @sethuster and I set export JAVA_HOME="$(/usr/libexec/java_home -v 1.8.0_65)" but when I run browsermob, I get the same error as above. 
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

Am I missing something?

**Comment by rtezera1** [comment]
BTW, I set it both in ~./bash_profile and ~/.profile because I am not sure which one it is reading from

**Comment by 5vxssbdahves** [comment]
@rtezera1 Have the same problem as you - did you solve it?
