### ISSUE TITLE
'isHttps' is already in use when using BrowserMobProxyServer

### ISSUE THREAD

**Issue by tav1313** [lightbody/browsermob-proxy#257]
16:00:52.799 ERROR- (AWAITING_INITIAL) [id: 0x9bac9cce, /fe80:0:0:0:8c09:c430:829:79a1%14:63523 => /fe80:0:0:0:8c09:c430:829:79a1%14:9100]: Caught an exception on ClientToProxyConnection
java.lang.IllegalArgumentException: 'isHttps' is already in use
	at io.netty.util.UniqueName.<init>(UniqueName.java:53) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]

what does it exactly means? there are several messages like that in logs

**Comment by jekh** [comment]
We really need more information about how you're using BMP in order to help. A small piece of a stack trace is rarely enough information to help you. What version of BMP are you using? What URL are you accessing? How are you executing the tests? What are the logs surrounding the request?

Make sure you're using the latest version of BMP, 2.1.0-beta-1, _not_ a recent -SNAPSHOT version. The netty version in the stack trace is from a previous BMP release.

**Comment by jekh** [comment]
Since there's been no activity here, I'm going to close the issue.

**Comment by slipwalker** [comment]
Hello. Probably I’ve faced the same issue. Just integrate BrowserMob littleproxy of version 2.0.1-beta-4 with my selenium tests (on Mac platform) and getting following at the opening by tests the localhost page of my web app (opened URL looks like http://localhost:8080/app/login):

[00002] WARN  n.l.b.f.BrowserMobHttpFilterChain - Filter in filter chain threw exception. Filter method may have been aborted.
java.lang.IllegalArgumentException: 'isHttps' is already in use
	at io.netty.util.UniqueName.<init>(UniqueName.java:53) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at net.lightbody.bmp.filters.HttpsAwareFiltersAdapter.isHttps(HttpsAwareFiltersAdapter.java:34) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at net.lightbody.bmp.filters.HttpsAwareFiltersAdapter.getFullUrl(HttpsAwareFiltersAdapter.java:100) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at net.lightbody.bmp.filters.RewriteUrlFilter.clientToProxyRequest(RewriteUrlFilter.java:50) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.clientToProxyRequest(BrowserMobHttpFilterChain.java:65) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:227) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:193) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:82) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]


And then when I try to open google search page by tests, I see another error and the page have not been opened:

[00002] ERROR o.l.p.impl.ClientToProxyConnection - (AWAITING_INITIAL) [id: 0x1405fe0f, /myIP:54148 => /myIP:13088]: Caught an exception on ClientToProxyConnection
java.lang.IllegalArgumentException: 'originalHost' is already in use
	at io.netty.util.UniqueName.<init>(UniqueName.java:53) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at net.lightbody.bmp.filters.HttpsOriginalHostCaptureFilter.<init>(HttpsOriginalHostCaptureFilter.java:23) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at net.lightbody.bmp.BrowserMobProxyServer$5.filterRequest(BrowserMobProxyServer.java:1430) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.<init>(BrowserMobHttpFilterChain.java:42) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at net.lightbody.bmp.BrowserMobProxyServer$1.filterRequest(BrowserMobProxyServer.java:342) ~[browsermob-core-littleproxy-2.1.0-beta-4.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:221) ~[littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:193) ~[littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:82) ~[littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135) ~[littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) ~[littleproxy-1.1.0-beta-bmp-10.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) ~[littleproxy-1.1.0-beta-bmp-10.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) [littleproxy-1.1.0-beta-bmp-10.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

Thanks in advance.

**Comment by jekh** [comment]
This is caused by an old version of Netty that contains a bug. I forget which version of Netty contains the fix, but I would recommend upgrading to the latest, which is currently 4.0.34.
