### ISSUE TITLE
Following exception raised during startup

### ISSUE THREAD

**Issue by vijayansrinivasan** [lightbody/browsermob-proxy#267]
ERROR StatusLogger Invalid URL D:/Dev/browsermob-proxy-2.1.0-beta-1/bin/conf/bmp-logging.yaml java.net.MalformedURLException: unknown protocol: d
```java
        at java.net.URL.<init>(URL.java:592)
        at java.net.URL.<init>(URL.java:482)
        at java.net.URL.<init>(URL.java:431)
        at java.net.URI.toURL(URI.java:1096)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFromUri(ConfigurationFactory.java:296)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:395)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:254)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:419)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:138)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:102)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
        at net.lightbody.bmp.proxy.Main$LogHolder.<clinit>(Main.java:30)
        at net.lightbody.bmp.proxy.Main.main(Main.java:51)
```

**Comment by jekh** [comment]
You can ignore this exception. It doesn'taffect the functionality, and it's been fixed in master by PR #258. Thanks for keeping watch, though!
