### ISSUE TITLE
BrowserMobProxy server ERROR org.littleshoot.proxy.impl.DefaultHttpProxyServer - Uncaught throwable

### ISSUE THREAD

**Issue by metasonic** [lightbody/browsermob-proxy#297]
BrowserMobProxy doesn't work while ProxyServer works perfectly.
I created a project and added the browsermob-dist-2.1.0-beta-2.jar (found in browsermob-proxy-2.1.0-beta-2\lib) and tried to run the example below but it doesn't work, please see attached code and error
Can anyone point out the issue with this code?
```
import java.io.File;
import java.io.IOException;
import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.client.ClientUtil;
import net.lightbody.bmp.core.har.Har;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class LoadTest {


	public static void main(String args[]) throws IOException {
			 // start the proxy
		 BrowserMobProxy server = new BrowserMobProxyServer();
		 server.start(0);
		 		 int port = server.getPort();
		 System.out.println(port);
		 		 // get the Selenium proxy object
		 Proxy proxy = ClientUtil.createSeleniumProxy(server);
		 		 // configure it as a desired capability
		 DesiredCapabilities capabilities = new DesiredCapabilities();
		 capabilities.setCapability(CapabilityType.PROXY, proxy);
		 		 // start the browser up
		 FirefoxDriver driver = new FirefoxDriver(capabilities);
		 		 // create a new HAR with the label "yahoo.com"
		 server.newHar("yahoo");
		 		 // open yahoo.com
		 driver.get("https://in.yahoo.com");
		 		 // get the HAR data
		 Har har = server.getHar();
		 		 // Write the HAR Data in a File
		 File harFile = new File("D:\\psstg1.har");
		 har.writeTo(harFile);
		 		 // Stop the BrowserMob Proxy Server
		 server.stop();
		 		 // Close the browser
		 driver.quit();
	}
}

[main] ERROR org.littleshoot.proxy.impl.DefaultHttpProxyServer - Uncaught throwable
java.lang.NoSuchMethodError: io.netty.channel.nio.NioEventLoopGroup.<init>(ILjava/util/concurrent/ThreadFactory;Ljava/nio/channels/spi/SelectorProvider;)V
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer$ServerGroup.initializeTransport(DefaultHttpProxyServer.java:547) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer$ServerGroup.ensureProtocol(DefaultHttpProxyServer.java:530) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer.doStart(DefaultHttpProxyServer.java:361) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer.start(DefaultHttpProxyServer.java:351) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer.access$1400(DefaultHttpProxyServer.java:82) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer$DefaultHttpProxyServerBootstrap.start(DefaultHttpProxyServer.java:881) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:352) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:362) ~[browsermob-dist-2.1.0-beta-2.jar:?]
	at com.cam4.automation.tests.cam4.msgprojecttests.LoadTest.main(LoadTest.java:23) ~[bin/:?]

```

WORKING CODE
```
		// start the proxy
		ProxyServer server = new ProxyServer(4456);
		server.start();
		// captures the moouse movements and navigations
		server.setCaptureHeaders(true);
		server.setCaptureContent(true);
		// get the Selenium proxy object
		Proxy proxy = server.seleniumProxy();
		// configure it as a desired capability
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.PROXY, proxy);
		// start the browser up
		WebDriver driver = new FirefoxDriver(capabilities);
		// create a new HAR with the label "apple.com"
		server.newHar("assertselenium.com");
		// open yahoo.com
		driver.get("http://assertselenium.com");
		driver.get("http://assertselenium.com/2012/10/30/transformation-from-manual-tester-to-a-selenium-webdriver-automation-specialist/");
		// get the HAR data
		Har har = server.getHar();
		server.stop();
		driver.quit();
```

**Comment by jekh** [comment]
This looks like a Netty version conflict. Are you including a separate version of Netty with your project? When using BrowserMob Proxy in embedded mode (using Java code), the preferred way to include BMP is to use a dependency management system like Maven or Ivy. Are you using a dependency management system?

**Comment by metasonic** [comment]
I only use the browser proxy jar,  no other reference.  Is there any workaround for this?

**Comment by jekh** [comment]
My suggestion is to use maven, ivy, or another dependency-management system to include the appropriate embedded-mode module. The browsermob-proxy-dist jar is not designed to be used this way.

If you don't want to use maven to manage your dependencies, you can view all required dependencies in the pom file or by and include those manually in your project. This is not a supported method of using BMP in Embedded Mode, but in theory it should work.

**Comment by jekh** [comment]
Since there hasn't been an update for a while, I'm going to go ahead and close this issue.
