### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by satybald** [lightbody/browsermob-proxy#305]
I've setup simple selenium script that opens a browse navigates to couple pages and closes it. I'm using little browsemob proxy. During execution of my script I get constantly. I guess proxy terminates connections suddenly. However, how can I find a cause for that?

I'm using browsermob-core-littleproxy", 2.1.0-beta-2

````
WARN [LittleProxy-ClientToProxyWorker-0] (ClientToProxyConnection.java:676) - (AWAITING_INITIAL) [id: 0xec8a40bf, /192.168.9.33:51763 => /192.168.9.33:51701]: Caught an exception on ClientToProxyConnection
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by satybald** [comment]
I think the issue was that I've setuped a timeouts. After I removed them everything seems okey:

```
    proxy.setConnectTimeout(5, TimeUnit.SECONDS);
    proxy.setRequestTimeout(5, TimeUnit.SECONDS);
```

**Comment by gridlastic-tj** [comment]
We also had this exact error when running tests at scale, it had to do with max open files and these [changes fixed it](https://www.gridlastic.com/gridlastic-connect.html#max_open_file_limit)

**Comment by jekh** [comment]
This is odd indeed. I haven't seen any other reports of this issue, so I'll go ahead and close. Please reopen if you continue to experience this problem.

**Comment by kirillbilchenko** [comment]
the same happening for me @jekh
