### ISSUE TITLE
httpProxy with user and password (user:password@10.10.10.10:8080)

### ISSUE THREAD

**Issue by eyal919** [lightbody/browsermob-proxy#310]
We have httpProxy configured in our system but we can't set the user and password.
When we set the proxy to be as follow: **httpProxy=http://user:password@10.10.10.10:8080** we getting the following expectation because of the split of the address by ':' .

It will be great if you support user and password in the address.

java.lang.NumberFormatException: For input string: "password@10.10.10.10"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at **net.lightbody.bmp.proxy.http.BrowserMobHttpClient.setHttpProxy(BrowserMobHttpClient.java:1353)**
	at net.lightbody.bmp.proxy.ProxyServer.start(ProxyServer.java:92)
	at com.taboola.testing.rbox.utils.proxy.ProxyUtils.getProxyThreadSafe(ProxyUtils.java:118)
	at com.taboola.testing.rbox.utils.proxy.ProxyUtils.getProxyThreadSafe(ProxyUtils.java:92)
	at com.taboola.testing.rbox.utils.proxy.ProxyUtils.createProxyServer(ProxyUtils.java:43)
	at co

**Comment by jekh** [comment]
Putting usernames and passwords in the URL is not a recommended practice, in fact I believe it is prohibited according to recent specs. But does this work with the browsermob-core-littleproxy module?

**Comment by eyal919** [comment]
Thanks,
Not an issue. Solved here: https://github.com/lightbody/browsermob-proxy/issues/294#issuecomment-133157389
