### ISSUE TITLE
Can't parse long-lived cookies

### ISSUE THREAD

**Issue by teleological** [lightbody/browsermob-proxy#311]
~~Netty 3~~ BrowserMob throws an exception when trying to parse a cookie where max-age > Integer.MAX_VALUE. On initiali inspection, it looked like a Netty 3 problem which had been corrected in Netty 4, but that may not be the case.

````
[WARN  2015-09-03T12:47:53,963 net.lightbody.bmp.filters.BrowserMobHttpFilterChain] (LittleProxy-ProxyToServerWorker-3) Filter in filter chain threw exception. Filter method may have been aborted. java.lang.NumberFormatException: For input string: "3153600000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_60]
	at java.lang.Integer.parseInt(Integer.java:583) ~[?:1.8.0_60]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_60]
	at io.netty.handler.codec.http.CookieDecoder.decode(CookieDecoder.java:128) ~[browsermob-dist-2.1.0-beta-2.jar:?]

**Comment by jekh** [comment]
AFAIK Netty 3 and 4 use entirely different package names, so it's not possible for BMP to call Netty 3 code. Do you know what version of Netty the fix was applied to? I can see about upgrading BMP to that version.

**Comment by DmitriyRomanov** [comment]
I also have experienced this error.
Filter in filter chain threw exception. Filter method may have been aborted.
java.lang.NumberFormatException: For input string: "1448439908.617"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at io.netty.handler.codec.http.CookieDecoder.doDecode(CookieDecoder.java:168)
	at io.netty.handler.codec.http.CookieDecoder.decode(CookieDecoder.java:77)
	at io.netty.handler.codec.http.CookieDecoder.decode(CookieDecoder.java:73)
	at net.lightbody.bmp.filters.HarCaptureFilter.captureResponseCookies(HarCaptureFilter.java:536)
	at net.lightbody.bmp.filters.HarCaptureFilter.captureResponse(HarCaptureFilter.java:512)
	at net.lightbody.bmp.filters.HarCaptureFilter.serverToProxyResponse(HarCaptureFilter.java:255)

I am using a 
browsermob-core-littleproxy :   2.1.0-beta-3
netty-all:  4.0.33.Final

**Comment by teleological** [comment]
Perhaps I was wrong in attributing the fault to Netty 3? Amending title.

**Comment by jekh** [comment]
Thanks, @DmitriyRomanov and @teleological. Are you still experiencing this issue with the latest beta-4? If so, we might need to update some of the cookie handling code; Netty replaced this in a recent 4.0 release, but BMP is still using the deprecated cookie handling.

**Comment by avietrov** [comment]
I experience similar issue on beta-4
> For input string: " 2592000"

**Comment by jekh** [comment]
@avietrov - Is there a web site that I can hit that will repro the issue you're seeing?

**Comment by jekh** [comment]
This issue should _finally_ be fixed! @teleological - let me know if you're still seeing it.

@avietrov - The issue you were seeing is different from @teleological's. There appears to be a space before the max-age value. That may be fixed now as well, let me know what you find.
