### ISSUE TITLE
bowerMobProxy.getPort() throws null pointer exception, any idea why that happened?

### ISSUE THREAD

**Issue by xueling978** [lightbody/browsermob-proxy#377]
I am using littleproxy to capture my http traffic.  I used this command to create a proxy
BrowserMobProxy  server = new BrowserMobProxyServer();

I generate a random port for newly created server

But sometimes, getPort() throws null pointer exception, any idea why that has happened?

Thanks,

**Comment by jekh** [comment]
Can you paste the stack trace from the exception?

**Comment by xuelinglou1978** [comment]
Sure.  Below please find the stack trace.  Thanks!

Exception Stack Trace: 

java.lang.NullPointerException at net.lightbody.bmp.BrowserMobProxyServer.getPort(BrowserMobProxyServer.java:435) at com.paypal.controller.rest.DASTProxyHomeRestController.returnProxyDetailsForSeleniumTests(DASTProxyHomeRestController.java:344) at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868) at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186) at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)

**Comment by jekh** [comment]
What version of BMP are you using?

**Comment by xuelinglou1978** [comment]
2.1.0-beta-2

I tried to use 2.1.0-beta-4 which caused problems to me.  Browser got navigation problem.

**Comment by jekh** [comment]
You'll definitely want to upgrade to beta-4. The CA certificate changed in beta-4. You'll want to install that in your browser as a trusted CA. It's in the sslSupport directory, and it's called ca-certificate-rsa.cer.

**Comment by xuelinglou1978** [comment]
All right, will try that and post an update here.  thanks!

**Comment by xuelinglou978** [comment]
Do you plan to implement a method to test whether proxy is running or not?  My use case will benefit from that function.  Thanks!

**Comment by jekh** [comment]
The isStarted() method returns true if the proxy has been started. I do not believe it is possible for proxyServer.getListenAddress() to return null unless LittleProxy fails to start, in which case an exception would be thrown when calling BrowserMobProxy.start(). Can you paste a stack trace from beta-4?

**Comment by xuelinglou978** [comment]
Hi, Jason,

I tried to upgrade once and got the same result.  Now I am not ready to
upgrade to beta-4 yet.

Thanks for your information.  I will try shortly.

Thanks,
Shirleen

**Comment by xuelinglou978** [comment]
06-Feb-2016 10:11:09.697 WARNING [LittleProxy-ClientToProxyWorker-0] net.lightbody.bmp.filters.HttpConnectHarCaptureFilter.populateServerIpAddress Unable to find cached IP address for host: www.stage2p1673.qa.paypal.com. IP address in HAR entry will be blank.
06-Feb-2016 10:11:09.697 INFO [LittleProxy-ClientToProxyWorker-0] org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial (AWAITING_INITIAL) [id: 0xf40c0259, /10.57.88.112:63217 => /10.185.168.144:27150]: Bad Host www.stage2p1673.qa.paypal.com:443
06-Feb-2016 10:11:19.244 WARNING [LittleProxy-ProxyToServerWorker-5] net.lightbody.bmp.filters.HarCaptureFilter.captureResponseContent No content type specified in response. Content will be treated as application/octet-stream
06-Feb-2016 10:11:20.135 WARNING [LittleProxy-ProxyToServerWorker-5] org.littleshoot.proxy.impl.ProxyToServerConnection.exceptionCaught (HANDSHAKING) [id: 0x21ca8350, /10.185.168.144:61966 => ak1s.abmr.net/23.60.101.149:443]: Caught exception on proxy -> web connection
 java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

06-Feb-2016 10:11:20.151 WARNING [LittleProxy-ProxyToServerWorker-5] org.littleshoot.proxy.impl.ProxyToServerConnection.exceptionCaught (HANDSHAKING) [id: 0x21ca8350, /10.185.168.144:61966 => ak1s.abmr.net/23.60.101.149:443]: Disconnecting open connection
06-Feb-2016 10:11:21.088 WARNING [LittleProxy-ProxyToServerWorker-1] net.lightbody.bmp.filters.HarCaptureFilter.captureResponseContent No content type specified in response. Content will be treated as application/octet-stream
06-Feb-2016 10:11:21.151 WARNING [LittleProxy-ProxyToServerWorker-3] org.littleshoot.proxy.impl.ProxyToServerConnection.exceptionCaught (HANDSHAKING) [id: 0xe2c39018, /10.185.168.144:61972 => ak1s.abmr.net/23.60.101.149:443]: Caught exception on proxy -> web connection
 java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

06-Feb-2016 10:11:21.166 WARNING [LittleProxy-ProxyToServerWorker-3] org.littleshoot.proxy.impl.ProxyToServerConnection.exceptionCaught (HANDSHAKING) [id: 0xe2c39018, /10.185.168.144:61972 => ak1s.abmr.net/23.60.101.149:443]: Disconnecting open connection
06-Feb-2016 10:11:21.276 WARNING [LittleProxy-ProxyToServerWorker-4] org.littleshoot.proxy.impl.ProxyToServerConnection.exceptionCaught (HANDSHAKING) [id: 0xdd5b580e, /10.185.168.144:61973 => cm.g.doubleclick.net/74.125.224.57:443]: Caught exception on proxy -> web connection
 java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

06-Feb-2016 10:11:21.291 WARNING [LittleProxy-ProxyToServerWorker-4] org.littleshoot.proxy.impl.ProxyToServerConnection.exceptionCaught (HANDSHAKING) [id: 0xdd5b580e, /10.185.168.144:61973 => cm.g.doubleclick.net/74.125.224.57:443]: Disconnecting open connection
06-Feb-2016 10:11:41.104 SEVERE [LittleProxy-ClientToProxyWorker-5] org.littleshoot.proxy.impl.ClientToProxyConnection.exceptionCaught (AWAITING_INITIAL) [id: 0xc0e21d8b, /10.57.88.112:63276 => /10.185.168.144:27150]: Caught an exception on ClientToProxyConnection
 java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xuelinglou978** [comment]
Once a while, I only see awaiting_initial no handshake any more.  I cannot migrate to beta-4 yet.  Will do that in the next couple of weeks.

**Comment by xueling978** [comment]
I actually need both isStarted() and isStopped() function.  Right now only isStarted() is accessible to me.

**Comment by xueling978** [comment]
I saw you post:
Yes, it is a bit confusing. Here's how isStarted() and isStopped() work:

Before the proxy is started, both isStarted() and isStopped() return false.
After starting the proxy, isStarted() returns true and isStopped() returns false.
After stopping the proxy, both isStarted() and isStopped() return true.
The meaning of isStarted() is not "is the proxy currently running?" but rather "was the proxy started at some point?". Perhaps we can consider adding an isRunning() or isActive() method that returns true only if the proxy is started and has not stopped.



For now, if you need to know whether the proxy is currently active, check condition #2 above, i.e. isStarted() == true && isStopped() == false. Unfortunately isStopped() is not specified in the BrowserMobProxy interface, only in BrowserMobProxyServer, so you'll need to use BrowserMobProxyServer directly, or downcast: ((BrowserMobProxyServer)proxyServer).isStopped(). I'll make a note to add isStopped() to the BrowserMobProxy interface.

Yes, isRunning() or isActive() is better.  My case is that I am not sure whether a proxy has been stopped or not, so I am trying to cleanup staled proxies.  Being able to tell whether a proxy is currently running or not is much helpful.

Thanks!

**Comment by jekh** [comment]
Since this seems to be "works-as-designed", I'll close the issue.
