### ISSUE TITLE
Getting error 'use-littleproxy false' is not a recognized option

### ISSUE THREAD

**Issue by stavanmehta** [lightbody/browsermob-proxy#387]
Command: 
sh /myproject/bin/browsermob/bin/browsermob-proxy --port=8080 --use-littleproxy false

Feb 18, 2016 5:55:28 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: joptsimple.UnrecognizedOptionException: 'use-littleproxy false' is not a recognized option
joptsimple.UnrecognizedOptionException: 'use-littleproxy false' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:93)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:402)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:55)
	at joptsimple.OptionParser.parse(OptionParser.java:392)
	at net.lightbody.bmp.proxy.guice.ConfigModule.configure(ConfigModule.java:57)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.lightbody.bmp.proxy.Main.main(Main.java:45)

Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=port) was bound.
  while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=port)
    for parameter 0 at net.lightbody.bmp.proxy.guice.JettyServerProvider.<init>(JettyServerProvider.java:19)
  at net.lightbody.bmp.proxy.guice.JettyModule.configure(JettyModule.java:10)

2) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=address) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=address)
    for parameter 1 at net.lightbody.bmp.proxy.guice.JettyServerProvider.<init>(JettyServerProvider.java:19)
  at net.lightbody.bmp.proxy.guice.JettyModule.configure(JettyModule.java:10)

3) An exception was caught and reported. Message: 'use-littleproxy false' is not a recognized option
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.lightbody.bmp.proxy.Main.main(Main.java:45)
Caused by: joptsimple.UnrecognizedOptionException: 'use-littleproxy false' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:93)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:402)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:55)
	at joptsimple.OptionParser.parse(OptionParser.java:392)
	at net.lightbody.bmp.proxy.guice.ConfigModule.configure(ConfigModule.java:57)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 4 more

**Comment by stavanmehta** [comment]
Closing as it works fine with browsermob-dist-2.1.0-beta-5-SNAPSHOT.jar
