### ISSUE TITLE
General SSLEngine problem

### ISSUE THREAD

**Issue by jpereira06** [lightbody/browsermob-proxy#439]
I'm using Selenium & browsermob-core-littleproxy(2.1.0-beta-6).

When trying to connect to https://www.maishaviajes.com/ I get the following error. 

I have added the property: 
`proxy.setTrustAllServers(true);`

How can I trust all ssl certs? Is this issue related with [437](https://github.com/lightbody/browsermob-proxy/issues/437) ?

javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1375) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:529) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:807) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:775) ~[na:1.8.0_25]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_25]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:970) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1708) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:303) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:876) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:873) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1313) ~[na:1.8.0_25]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1124) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	... 13 common frames omitted
Caused by: java.security.cert.CertificateException: No name matching www.maishaviajes.com found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:208) ~[na:1.8.0_25]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[na:1.8.0_25]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_25]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:941) ~[na:1.8.0_25]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:880) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1458) ~[na:1.8.0_25]
	... 21 common frames omitted

2016-04-25 15:55:18.588 ERROR 10306 --- [oServerWorker-0] o.l.proxy.impl.ProxyToServerConnection   : (DISCONNECTED) [id: 0xf41b8fda, L:0.0.0.0/0.0.0.0:62104 ! R:www.maishaviajes.com/109.70.38.51:443]: Caught an exception on ProxyToServerConnection

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:418) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.36.Final.jar:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1375) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:529) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:807) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:775) ~[na:1.8.0_25]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_25]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:970) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	... 11 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_25]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1708) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:303) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:876) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:873) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1313) ~[na:1.8.0_25]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1124) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
	... 13 common frames omitted
Caused by: java.security.cert.CertificateException: No name matching www.maishaviajes.com found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:208) ~[na:1.8.0_25]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[na:1.8.0_25]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_25]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:941) ~[na:1.8.0_25]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:880) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1458) ~[na:1.8.0_25]
	... 21 common frames omitted

**Comment by jekh** [comment]
Yes, this is an instance of #471. Did this change since beta-5?

**Comment by jpereira06** [comment]
No, I get the same error with beta-5

**Comment by jekh** [comment]
That's good-ish news. Since this is open as a bug in 437, I'll close this issue and track it there.

**Comment by jekh** [comment]
@jpereira06 - This should now be fixed in master. Let me know if you still have issues, though.

**Comment by jpereira06** [comment]
@jekh I'm getting the same error with "2.1.0-beta-7-SNAPSHOT"

**Comment by jekh** [comment]
I just tried https://www.maishaviajes.com/ and it loaded successfully with the latest code in master. You do need to call setTrustAllServers(true) _before_ starting the proxy, though (the site's SSL certificate is invalid).

**Comment by jpereira06** [comment]
Yes, you are right. I missed the setTrustAllServers(true) . Sorry.

**Comment by jekh** [comment]
No worries, glad it works for you now!
