### ISSUE TITLE
No subject alternative names matching IP address

### ISSUE THREAD

**Issue by seveniruby** [lightbody/browsermob-proxy#443]
use the default cer file 
when app send request with https://x.x.x.x./xxx  it will show error with 
```
 java.security.cert.CertificateException: No subject alternative names matching IP address 
```

how can i apply setHostnameVerifier to the default proxy server instance

when use old ProxyServer,  there's no error

**Comment by jekh** [comment]
This was ultimately caused by #437, which is now fixed in master. You still have to set the trustAllServers option to true in order to bypass upstream server checks, though. I'll close this, but feel free to reopen if you're still having issues.

**Comment by seveniruby** [comment]
still exist when using 2.1.1
```
    val proxyServer = new BrowserMobProxyServer()
    proxyServer.setTrustAllServers(true)
    proxyServer.start(port)

    proxyServer.setHarCaptureTypes(CaptureType.getNonBinaryContentCaptureTypes)
    proxyServer.setHarCaptureTypes(CaptureType.getHeaderCaptureTypes)

    val dns=ClientUtil.createDnsJavaResolver()
    hosts.foreach(m=>dns.remapHost(m._1, m._2))
    proxyServer.setHostNameResolver(dns)

```

**Comment by jekh** [comment]
You're facing a different issue, where the hostname remapping is most likely not cooperating properly with the server and/or client connection over HTTPS. Can you paste the stack trace?

**Comment by seveniruby** [comment]
```
20:00:38.961 [LittleProxy-0-ProxyToServerWorker-6] DEBUG n.l.b.m.t.InsecureExtendedTrustManager - Accepting an untrusted server certificate: CN=*.xxxxxx.com, OU=Domain Control Validated - RapidSSL(R), OU=See www.rapidssl.com/resources/cps (c)15, OU=GT56830585
java.security.cert.CertificateException: No subject alternative names matching IP address xx.xx.xx.xx found
        at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:167) ~[na:1.8.0_51]
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[na:1.8.0_51]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_51]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[na:1.8.0_51]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[na:1.8.0_51]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[na:1.8.0_51]
        at net.lightbody.bmp.mitm.trustmanager.InsecureExtendedTrustManager.checkServerTrusted(InsecureExtendedTrustManager.java:95) ~[net.lightbody.bmp.mitm-2.1.1.jar:na]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1484) [na:1.8.0_51]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) [na:1.8.0_51]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) [na:1.8.0_51]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) [na:1.8.0_51]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) [na:1.8.0_51]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_51]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) [na:1.8.0_51]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1124) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [io.netty.netty-all-4.0.36.Final.jar:4.0.36.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

```

**Comment by jekh** [comment]
The DEBUG statement says `Accepting an untrusted server certificate`. This is working as designed. It is trusting the certificate. Are you experiencing an issue, or just noticing the log statement? You can set the log level to INFO to get rid of debugging information.

**Comment by seveniruby** [comment]
i just found the reason.
i installed the cer file to my android device when bmp in version 2.1.0.xxx or older
but after version 2.1.1, the cer file have been updated and i did't notice this change. 
so when i just upgrade the library and code without the new cer file,  the ssl connections would fail everytime. but when i use burpsuite do samething, everything just worked
so my first doubt is the warning message in debug level and which was the only warning message. 

until today, i follow the code with #445 and  read the README again to try find what'new . i just notice the certificate file change after 2.1.1.  i install the new cer file to device and do the testing.  everything work again.  :)
