### ISSUE TITLE
Unable to use BrowserMob Proxy for app

### ISSUE THREAD

**Issue by narulacool** [lightbody/browsermob-proxy#449]
I am trying to use BrowserMob Proxy for my app using appium. The issue is that the app just quits on the following line:
BrowserMobProxy proxy =  new BrowserMobProxyServer();

The error is as below:
`java.lang.NoSuchFieldError: as_sys_sec_alg_ideaCBC
                        	at org.bouncycastle.jcajce.provider.symmetric.IDEA$Mappings.configure(Unknown Source)
                        	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source)
                        	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
                        	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
                        	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
                        	at java.security.AccessController.doPrivileged(Native Method)
                        	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
                        	at net.lightbody.bmp.mitm.tools.BouncyCastleSecurityProviderTool.<clinit>(BouncyCastleSecurityProviderTool.java:62)
                        	at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.<init>(DefaultSecurityProviderTool.java:34)
                        	at net.lightbody.bmp.mitm.util.TrustUtil.<clinit>(TrustUtil.java:51)
                        	at net.lightbody.bmp.mitm.TrustSource.javaTrustSource(TrustSource.java:103)
                        	at net.lightbody.bmp.mitm.TrustSource.<clinit>(TrustSource.java:39)
                        	at net.lightbody.bmp.BrowserMobProxyServer.<init>(BrowserMobProxyServer.java:251)
                        	at net.lightbody.bmp.BrowserMobProxyServer.<init>(BrowserMobProxyServer.java:326)
                        	at Drivers.HamburgerDashBoard.TC_HBDashboard_004_ZeroRecommendedJobsPage(HamburgerDashBoard.java:556)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        	at java.lang.reflect.Method.invoke(Method.java:483)
                        	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
                        	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
                        	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
                        	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
                        	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
                        	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
                        	at org.testng.TestRunner.privateRun(TestRunner.java:774)
                        	at org.testng.TestRunner.run(TestRunner.java:624)
                        	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
                        	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
                        	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
                        	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
                        	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                        	at java.lang.Thread.run(Thread.java:745)
                     `

**Comment by narulacool** [comment]
Just to mention I am using browsermob-dist-2.1.0-beta-6.jar

**Comment by narulacool** [comment]
Please update on the issue as I am stuck on this.

**Comment by jekh** [comment]
You say you're using `browsermob-dist-2.1.0-beta-6.jar`; are you running BMP in standalone mode from the command line, then?

The error you've pasted is indicative of an old version of bouncycastle on your classpath, but that wouldn't make sense if you're running from the command line. If you're running BMP in embedded mode, you shouldn't be using the -dist- jar. See the README file for instructions.

**Comment by narulacool** [comment]
I am trying to run it in embedded mode. 
I even tried adding  browsermob-core-2.1.0-beta-6-sources.jar into my project. But using this jar I simply can't get the imports for :
BrowserMobProxy proxy = new BrowserMobProxyServer();
![screen shot 2016-05-14 at 12 06 52 am](https://cloud.githubusercontent.com/assets/11459167/15258198/d188d9b8-1967-11e6-9708-1666cf2605eb.png)

**Comment by jekh** [comment]
I suggest you use a dependency management system, such as Maven or Gradle. Attempting to manually include dependencies is an extremely painful process.
