### ISSUE TITLE
Getting "java.lang.NoSuchFieldError: as_sys_sec_alg_ideaCBC" with version 2.1.0

### ISSUE THREAD

**Issue by yotam-supersonic** [lightbody/browsermob-proxy#463]
Hi all,

I recently upgraded from 2.1.0 beta to the latest 2.1.0, and I when I call `new BrowserMobProxyServer()` keep getting the following exception:

```
java.lang.NoSuchFieldError: as_sys_sec_alg_ideaCBC

	at org.bouncycastle.jcajce.provider.symmetric.IDEA$Mappings.configure(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
	at net.lightbody.bmp.mitm.tools.BouncyCastleSecurityProviderTool.<clinit>(BouncyCastleSecurityProviderTool.java:63)
	at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.<init>(DefaultSecurityProviderTool.java:34)
	at net.lightbody.bmp.mitm.util.TrustUtil.<clinit>(TrustUtil.java:51)
	at net.lightbody.bmp.mitm.TrustSource.javaTrustSource(TrustSource.java:103)
	at net.lightbody.bmp.mitm.TrustSource.<clinit>(TrustSource.java:39)
	at net.lightbody.bmp.BrowserMobProxyServer.<init>(BrowserMobProxyServer.java:219)
```

Did a little reading and I saw that I might be related to Bouncy Castle. I downloaded the latest version (tried both `bcprov-jdk15on-154.jar` and `bcprov-ext-jdk15on-154.jar`) and now I'm getting

```
java.lang.ExceptionInInitializerError
	at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.<init>(DefaultSecurityProviderTool.java:34)
	at net.lightbody.bmp.mitm.util.TrustUtil.<clinit>(TrustUtil.java:51)
	at net.lightbody.bmp.mitm.TrustSource.javaTrustSource(TrustSource.java:103)
	at net.lightbody.bmp.mitm.TrustSource.<clinit>(TrustSource.java:39)
	at net.lightbody.bmp.BrowserMobProxyServer.<init>(BrowserMobProxyServer.java:219)
Caused by: java.lang.SecurityException: class "org.bouncycastle.jcajce.provider.symmetric.IDEA$Mappings"'s signer information does not match signer information of other classes in the same package
```

Did some more reading and seems like I might import the same jar twice, with one version signed (the one I downloaded) and the other one not. I checked and I don't import it more than once.

A little helpless here, any suggestions?

Thanks!

**Comment by jekh** [comment]
What are you using to manage dependencies? Maven, gradle, ivy, something else? Are you setting the version of bouncy castle to something other than what ships with BMP?

**Comment by yotam-supersonic** [comment]
I'm using IntelliJ to directly attach all my Jars. I'm not sure how it's done behind the scene, relatively new to Java.
<img width="1025" alt="screen shot 2016-05-30 at 07 02 40" src="https://cloud.githubusercontent.com/assets/12996754/15639461/aa9a19aa-2634-11e6-81cd-4f484b641360.png">

**Comment by jekh** [comment]
You'll want to use Gradle or Maven. Manual dependency management is not going to be fruitful for you.

**Comment by yotam-supersonic** [comment]
That's very true, thanks you. The problem was solved when I removed selenium-standalone-server :)

**Comment by JayatejaG** [comment]
Hi ,
Iam getting below exception
java.lang.NoSuchFieldError: as_sys_sec_alg_ideaCBC
	at org.bouncycastle.jcajce.provider.symmetric.IDEA$Mappings.configure(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
	at net.lightbody.bmp.mitm.tools.BouncyCastleSecurityProviderTool.<clinit>(BouncyCastleSecurityProviderTool.java:63)
	at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.<init>(DefaultSecurityProviderTool.java:34)
	at net.lightbody.bmp.mitm.util.TrustUtil.<clinit>(TrustUtil.java:56)
	at net.lightbody.bmp.mitm.TrustSource.javaTrustSource(TrustSource.java:103)
	at net.lightbody.bmp.mitm.TrustSource.<clinit>(TrustSource.java:39)
	at net.lightbody.bmp.BrowserMobProxyServer.<init>(BrowserMobProxyServer.java:225)
	at com.mob.SimpleTest.getProxyServer(SimpleTest.java:47)
	at com.mob.SimpleTest.test(SimpleTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)


I am using below maven dependencies
<dependency>
    <groupId>net.lightbody.bmp</groupId>
    <artifactId>browsermob-proxy</artifactId>
    <version>2.0-beta-8</version>
</dependency>
<dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>browsermob-core</artifactId>
        <version>2.1.5</version>
        <scope>test</scope>
    </dependency>
