### ISSUE TITLE
net.lightbody.bmp.filters.HarCaptureFilter Unable to decode query parameters on URI

### ISSUE THREAD

**Issue by djtm** [lightbody/browsermob-proxy#480]
This happens loading heise.de. Not sure whether it's a bug in LP or BM?

```
[INFO  2016-06-16T09:25:41,377 net.lightbody.bmp.filters.HarCaptureFilter] (LittleProxy-0-ClientToProxyWorker-4) Unable to decode query parameters on URI: http://s79.research.de.com/bb-mx/prime/mtrcs_914558.js?pjid=914558&adc=Intern_Mediacom_Volkswagen%20Nutzfahrzeuge&cpid=656782&apb=23207&apa=ADGapID_026_800138_418765277-418765277&place=17406962&cid=35309357&site=[%tp_LineID%]&size=1x1&cb=[timestamp] java.lang.IllegalArgumentException: invalid escape sequence `%tp' at index 1 of: [%tp_LineID%]
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:352) ~[browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.codec.http.QueryStringDecoder.decodeParams(QueryStringDecoder.java:239) ~[browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.codec.http.QueryStringDecoder.parameters(QueryStringDecoder.java:204) ~[browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.HarCaptureFilter.captureQueryParameters(HarCaptureFilter.java:327) [browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.HarCaptureFilter.clientToProxyRequest(HarCaptureFilter.java:206) [browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.clientToProxyRequest(BrowserMobHttpFilterChain.java:65) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:227) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:191) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:80) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277) [browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [browsermob-dist-2.1.1.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [browsermob-dist-2.1.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

probably unrelated

```
[WARN  2016-06-16T09:25:55,527 net.lightbody.bmp.filters.ServerResponseCaptureFilter] (LittleProxy-0-ProxyToServerWorker-4) Cannot decode unsupported content encoding type UTF-8 
[WARN  2016-06-16T09:25:55,530 net.lightbody.bmp.filters.HarCaptureFilter] (LittleProxy-0-ProxyToServerWorker-4) Unable to decompress content with encoding: UTF-8. Contents will be encoded as base64 binary data.
```

**Comment by jekh** [comment]
It's not a bug in LP or BMP, it's a bug in the website you're visiting. The message in the exception says `java.lang.IllegalArgumentException: invalid escape sequence '%tp' at index 1 of: [%tp_LineID%]`. This is because neither `%t` nor `%]` are legal character sequences in a URL. BMP handles the request/response fine, it just can't decode the query parameters for the HAR.

The second exception is also a bug in the website you're visiting. It appears the site has conflated Content-Encoding and Content-Type. For more info, see https://tools.ietf.org/html/rfc7231#section-3.1.2.1

**Comment by djtm** [comment]
Thanks for the clarification. I assume no bug compatibility is planed. The errors appear to slow down at finishing the loading process of a page, which causes selenium to hang. Do you happen to know a workaround?

**Comment by jekh** [comment]
No work-arounds are planned; the request is handled properly, it just doesn't list query params individually in the HAR. The rest of the HAR fields for the request should still be there too, including the full URL. For the invalid Content-Encoding, the data is still present in the HAR, it's just base64-encoded (since 'UTF-8' is a nonsensical Content-Encoding, that's pretty much the best we can do). The request should still be handled properly, though.

Any hangs are most likely caused by something else. It could be the server is actually failing to respond, or there could be some other error in BMP that is causing the request to abort/hang. For the latter scenario, there would almost certainly be some output in the BMP log file. Do you see any unhandled exceptions or other suspicious messages there?

**Comment by djtm** [comment]
Well but the hangs don't occur with plain Google Chrome. Could it be that either Java has pretty high network timeouts by default or Google Chrome has higher timeouts when using a proxy?
The load time jumps from aroud 10 seconds to over 60 seconds. Should I open a new bug and post some HARs and logs? Or should I post them here?

**Comment by jekh** [comment]
Yes, if you're seeing hangs, please do open an issue and include BMP logs, the code you use to start BMP, and any steps to reproduce. That would be extremely helpful!

**Comment by gtpvkr** [comment]
even i'm too facing same issue, is there any work around or solution for this?

thanks in advance!!
