### ISSUE TITLE
HTTPS issue on 2.1.1 version

### ISSUE THREAD

**Issue by sskorol** [lightbody/browsermob-proxy#483]
Hi @jekh,

I'm currently using BMP 2.1.0-beta-5-SNAPSHOT (built manually from sources) for capturing https requests / responses. It works fine to me. I did only 2 things to make it works: added [ca-certificate-rsa.cer](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/resources/sslSupport/ca-certificate-rsa.cer) and our web app's cert into Trusted Root.

When I updated BMP to 2.1.1 version, I can't track https traffic anymore. On BMP side I see the following errors.
<details> 
  <summary><a id="spoiler2" href="#spoiler2" title="error log">Error log</a></summary>
[ERROR 2016-06-18T17:20:10,832 org.littleshoot.proxy.impl.ProxyToServerConnectio
n] (LittleProxy-0-ProxyToServerWorker-2) (DISCONNECTED) [id: 0x110d1158, L:0.0.0
.0/0.0.0.0:63518 ! R:ptx-dev-app02.bts.local/10.2.3.24:443]: Caught an exception
 on ProxyToServerConnection io.netty.handler.codec.DecoderException: javax.net.s
sl.SSLHandshakeException: General SSLEngine problem
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:418) ~[browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:245) ~[browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:962) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:131) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:528) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:485) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:399) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [browser
mob-dist-2.1.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:112) [browsermob-dist-2.1.1.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Unknown Source) ~[?:1.8.0_91]

        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source) ~[?:1.
8.0_91]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[?:1.8.
0_91]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[?:1.8.0_91]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[?:1.8.0_91]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) ~[browse
rmob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:970) ~[browser
mob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) ~[browser
mob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:387) ~[browsermob-dist-2.1.1.jar:?]
        ... 11 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[?:1.8.0_91]

        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~
[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:
1.8.0_91]
        at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.8.0_91]

        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_
91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source) ~[?:1.8
.0_91]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:112
4) ~[browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) ~[browse
rmob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) ~[browser
mob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:387) ~[browsermob-dist-2.1.1.jar:?]
        ... 11 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed:
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find vali
d certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:1.8.
0_91]
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~
[?:1.8.0_91]
        at sun.security.validator.Validator.validate(Unknown Source) ~[?:1.8.0_9
1]
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:1.
8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[
?:1.8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Sour
ce) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~
[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:
1.8.0_91]
        at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.8.0_91]

        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_
91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source) ~[?:1.8
.0_91]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:112
4) ~[browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) ~[browse
rmob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) ~[browser
mob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:387) ~[browsermob-dist-2.1.1.jar:?]
        ... 11 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to
 find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Sourc
e) ~[?:1.8.0_91]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown
 Source) ~[?:1.8.0_91]
        at java.security.cert.CertPathBuilder.build(Unknown Source) ~[?:1.8.0_91
]
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[?:1.8.
0_91]
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~
[?:1.8.0_91]
        at sun.security.validator.Validator.validate(Unknown Source) ~[?:1.8.0_9
1]
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[?:1.
8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[
?:1.8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Sour
ce) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~
[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:
1.8.0_91]
        at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.8.0_91]

        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_
91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source) ~[?:1.8
.0_91]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:112
4) ~[browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) ~[browse
rmob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) ~[browser
mob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:387) ~[browsermob-dist-2.1.1.jar:?]
        ... 11 more 
</details>

Any idea how to fix that (assuming that I'm using BMP via REST)? Please note that I'm able to use it with e.g. Google https traffic. But it fails with our app.

**Comment by jekh** [comment]
It looks like the certificate your app is using is not signed by a CA in BMP's trust store. By default, BMP uses the Java trust store + the Mozilla trust store (via curl at https://curl.haxx.se/ca/cacert.pem). If you're using self-signed certs in your app, or certs signed by an internal CA, they won't be trusted by default.

The easiest way to solve this problem when using the REST API is to set the trustAllServers parameter to true when creating a new proxy. For example:
```sh
 curl -X POST 'http://localhost:8080/proxy?useEcc=true&trustAllServers=true'
```

You can also add the certificates to the Java trust store. The new version of the REST API will have support for adding individual X.509 certificates to BMP's trust source, which will allow you to run your proxy without disabling certificate validation entirely.

**Comment by sskorol** [comment]
Thanks @jekh. Will check it tomorrow and let you know.

**Comment by sskorol** [comment]
@jekh,

```
trustAllServers=true
```
works like a charm, thanks!
