### ISSUE TITLE
No subject alternative DNS name matching some.site.com found

### ISSUE THREAD

**Issue by abotalov** [lightbody/browsermob-proxy#485]
When running Selenium tests using Browsermob REST proxy (browsermob-proxy-2.1.1-bin.zip) I get an error when tests try to access https website. Website's certificate is invalid (SSL_ERROR_BAD_CERT_DOMAIN). 

Proxy server is started using `browsermob-proxy.bat -port 9090`. Proxy is started using `useEcc=true&trustAllServers=true` so I would expect no errors to appear. VPN is turned on. Windows' hosts file contains an entry for a website. Overriding normal DNS lookups using `/proxy/[port]/hosts` doesn't help (same error appears).

JDK is 8u91.

Is there something I can try to resolve it?

```
[INFO  2016-06-20T17:45:11,951 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-0-ProxyToServerWorker-0) (HANDSHAKING) [id: 0xb66d14c7, L:0.0.0.0/0.0.0.0:61539 ! R:some.site.com/10.4.6.1:443]: Connection to upstream server failed javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[?:1.8.0_91]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[?:1.8.0_91]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1098) [browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:970) [browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:904) [browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) [browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [browsermob-dist-2.1.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [browsermob-dist-2.1.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [browsermob-dist-2.1.1.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source) ~[?:1.8.0_91]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1124) [browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) [browsermob-dist-2.1.1.jar:?]
        ... 13 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching some.site.com found.
        at sun.security.util.HostnameChecker.matchDNS(Unknown Source) ~[?:1.8.0_91]
        at sun.security.util.HostnameChecker.match(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source) ~[?:1.8.0_91]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1124) ~[browsermob-dist-2.1.1.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1009) ~[browsermob-dist-2.1.1.jar:?]
        ... 13 more

```

**Comment by jekh** [comment]
It definitely looks like the trustAllServers option isn't being specified. There should be a WARN-level message in the logs about disabling certificate validation. Is that there?

**Comment by abotalov** [comment]
I'm sorry. This was a user error. `trustAllServers` option was not specified.
