### ISSUE TITLE
Some requests not sent via proxy on SUSE Linux

### ISSUE THREAD

**Issue by anandbagmar** [lightbody/browsermob-proxy#492]
Hi,
I have integrated browsermob-proxy with my protractor tests. This works wonderfully when I run my tests from Mac (against local environment, or any other test environment).

However, when I run my tests from CI (agent is SUSE Enterprise 11.4) - my tests fail. I narrowed down the problem to the following scenario:
### On some specific user action in the UI, there are a lot (>100) of requests fired from the browser in parallel (batches). There are a couple of scenarios like this in my application - and the test fails in all these cases.

Here is a screenshot of what the captured HAR file shows (in this case - 

<img width="1188" alt="screen shot 2016-07-06 at 9 01 04 am" src="https://cloud.githubusercontent.com/assets/502964/16606803/98932ef4-4358-11e6-9704-5a616805826c.png">

> The same test works when I run this locally from Mac 

Any idea how to fix this? Thank you in advance!

###  Some more information 
> I am starting the proxy server using a separate shell script
./browsermob-proxy-2.1.1/bin/browsermob-proxy --port $port --address $hostname &>$bmpLogDir/bmpProxy.log &

> From my protractor tests - I start capture of the HAR file using this command:
{quote}
....
        var captureHeaders = true;
        var captureContent = true;
        var captureBinaryContent = false;
        browser.params.proxy.startHAR(browser.params.proxyData.port, name, captureHeaders, captureContent, captureBinaryContent, done);
{quote}

**Comment by anandbagmar** [comment]
Some more context - the same test in CI passes if I do not start the proxy server. 

Infant, after narrowing down the problem to the type of requests - I also tried the following:
> start proxy server before running tests
> startHAR capture at specific point
> saveHAR before the action that causes failures

Even with this, my test fails. This means that having the proxy-server started may be the issue ....

**Comment by jekh** [comment]
Is there anything suspicious in the BMP log itself? Anything at the WARN or ERROR level that might point in the direction of the problem?

**Comment by anandbagmar** [comment]
not really - the only 2 warnings I see are below:

```
[INFO  2016-07-08T08:06:59,511 net.lightbody.bmp.proxy.Main] (main) Starting BrowserMob Proxy version 2.1.1 
[INFO  2016-07-08T08:06:59,547 org.eclipse.jetty.util.log] (main) jetty-7.x.y-SNAPSHOT 
[INFO  2016-07-08T08:06:59,574 org.eclipse.jetty.util.log] (main) started o.e.j.s.ServletContextHandler{/,null} 
[INFO  2016-07-08T08:06:59,713 org.eclipse.jetty.util.log] (main) Started SelectChannelConnector@localhost:7070 
[INFO  2016-07-08T08:07:00,612 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1667305539-17) Starting proxy at address: localhost/127.0.0.1:7075 
[INFO  2016-07-08T08:07:00,627 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1667305539-17) Proxy listening with TCP transport 
[INFO  2016-07-08T08:07:00,664 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1667305539-17) Proxy started at address: /127.0.0.1:7075 
[INFO  2016-07-08T08:07:07,966 net.lightbody.bmp.proxy.ProxyManager] (qtp1667305539-16) Proxy already exists at port 7075 
[WARN  2016-07-08T08:10:12,864 net.lightbody.bmp.filters.HarCaptureFilter] (LittleProxy-0-ProxyToServerWorker-0) No content type specified in response from http://my.host.com/s/info?f=firstname,lastname,uid,email,company. Content will be treated as application/octet-stream 
[WARN  2016-07-08T08:10:26,231 net.lightbody.bmp.filters.HarCaptureFilter] (LittleProxy-0-ProxyToServerWorker-0) No content type specified in response from http://my.host.com/s/info?f=firstname,lastname,uid,email,company. Content will be treated as application/octet-stream 
```

The only place I can probably narrow down is triggering a large number of requests in parallel from the browser and the proxy running at that time.

Is there any limit to how many concurrent requests the browsermob-proxy can handle (especially on linux)?

**Comment by anandbagmar** [comment]
@jekh @lightbody 
I think I have more information - I do see a lot of warnings - but also this exception popped up in the browsermob-proxy:

PS: The 1st warning message show most likely has no relation to the exception seen.

```
[WARN  2016-07-11T09:31:56,651 net.lightbody.bmp.filters.HarCaptureFilter] (LittleProxy-0-ProxyToServerWorker-4) No content type specified in response from http://localhost:9000/api/services//170?tenantid=90. Content will be treated as application/octet-stream 
[WARN  2016-07-11T09:31:56,697 net.lightbody.bmp.filters.BrowserMobHttpFilterChain] (LittleProxy-0-ProxyToServerWorker-7) Filter in filter chain threw exception. Filter method may have been aborted. java.lang.NullPointerException
	at io.netty.handler.codec.http.HttpHeaders.getHeader(HttpHeaders.java:621) ~[browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.ServerResponseCaptureFilter.captureContentEncoding(ServerResponseCaptureFilter.java:142) ~[browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.ServerResponseCaptureFilter.serverToProxyResponse(ServerResponseCaptureFilter.java:97) ~[browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.HarCaptureFilter.serverToProxyResponse(HarCaptureFilter.java:251) ~[browsermob-dist-2.1.1.jar:?]
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.serverToProxyResponse(BrowserMobHttpFilterChain.java:123) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.respond(ClientToProxyConnection.java:418) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.respondWith(ProxyToServerConnection.java:534) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.readHTTPChunk(ProxyToServerConnection.java:240) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:146) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.read(ProxyToServerConnection.java:216) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection$ResponseReadMonitor.channelRead(ProxyConnection.java:738) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277) [browsermob-dist-2.1.1.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [browsermob-dist-2.1.1.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [browsermob-dist-2.1.1.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [browsermob-dist-2.1.1.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [browsermob-dist-2.1.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
```

**Comment by jekh** [comment]
This is a very interesting issue. The only thing that I can see that would cause the first NullPointerException is if LittleProxy processes the LastHttpContent before it finishes processing the first HttpResponse. Technically, this is possible, and BMP is not currently set up to handle this; though in reality it's very rare.

I've merged a PR that should fix the NPE, though it might still cause other strange issues to occur if messages are indeed being processed out-of-order. Can you build the latest code from master and test? And are you able to reproduce this consistently against a certain URL? I'd like to be able to debug locally, if possible.

**Comment by anandbagmar** [comment]
Hi @jekh ,
Thanks for fixing this! I will try it out with a local build and get back to you guys with the update. 

PS: Is this command (mvn -DskipTests -P release) the correct one to generate the latest build for testing?

Also, this is a consistently reproducible problem for me. What URL / info would you want to see for this to debug locally?

**Comment by anandbagmar** [comment]
Hi @jekh  - I just tested this locally - and this works 👍 

Thank you so much for the fix!! When is v2.1.2 expected to be released?

**Comment by jekh** [comment]
Thanks @anandbagmar, glad this fixed it. I would like to repro it locally though, to confirm whether it's processing messages out-of-order, or whether something else is going on. Is the URL you're hitting publicly accessible on the internet?

I was planning on putting out another release within the next couple days, most likely this weekend.

**Comment by anandbagmar** [comment]
Hi @jekh  - unfortunately this is not a public url. But I will try to get a relevant code snippet / or create a sample page for this that hopefully is of help to you. 

Looking forward to the new release! Thanks again

**Comment by jekh** [comment]
@anandbagmar - 2.1.2 is out now, so I'll close this issue. If you update it with steps to reproduce that work for you, I will do some investigation and see if I can fix the underlying issue.
