### ISSUE TITLE
Connection to upstream server failed with ClosedChannelException 	

### ISSUE THREAD

**Issue by anandbagmar** [lightbody/browsermob-proxy#517]
Hi @jekh , @lightbody ,

Using the latest release of BMP 2.1.2, I was able to resolve the issue reported earlier (https://github.com/lightbody/browsermob-proxy/issues/492) when running tests from my local machine. Today, when I deployed this change in my CI, I am seeing a new error - this is what I see in the proxy.log file:

```
[INFO  2016-07-26T07:41:02,791 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-0-ProxyToServerWorker-2) (HANDSHAKING) [id: 0xc1e3588f, L:0.0.0.0/0.0.0.0:55619 ! R:maps.googleapis.com/209.85.232.95:443]: Connection to upstream server failed java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) ~[browsermob-dist-2.1.2.jar:?]
```

Any idea why this may be happening? As a result, my protractor tests just block and then eventually timeout.

**Comment by jekh** [comment]
Are there any URLs you're hitting that we can test against? That'll help determine the source of the problem.

Just FYI, don't address issues to specific people. Anybody who's monitoring the issues may chime in if they have a solution.

**Comment by anandbagmar** [comment]
Apologise for tagging specific people, and for the delay in getting back on this issue.

I have been seeing some weird behaviour - where I do not see this issue anymore, but see the older issue #492 come back. Request some more time to investigate and get back on this one before you close this as not an issue.

**Comment by anandbagmar** [comment]
Hi, apologise for the delay. I get the problem intermittently. I have attached the BMP logs when this problem occurred. I am guessing as a result of this problem, the requests do not complete (see below screenshot) - and of course my tests fail. Does this log help? 

<img width="1194" alt="screen shot 2016-08-16 at 2 12 37 pm" src="https://cloud.githubusercontent.com/assets/502964/17693247/886acca2-63bb-11e6-970d-6ffa2b885432.png">

[bmpProxy.txt](https://github.com/lightbody/browsermob-proxy/files/419836/bmpProxy.txt)

**Comment by anandbagmar** [comment]
Hi, any clues why this would be happening?

**Comment by pkolenic** [comment]
I am having the same issues, though for me it occurs locally on my MAC.
If I run a test suite against 20 urls, sometimes all the tests will pass; other times some tests will fail for up to 5 urls.  The failures occur as the result of certain network calls not being present in the HAR to validate the call parameters.  

The log entries in BMP for the corresponding failing tests include:

[INFO  2016-11-22T09:58:38,233 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-0-ProxyToServerWorker-2) (HANDSHAKING) [id: 0xa4536777, L:0.0.0.0/0.0.0.0:49833 ! R:www.google-analytics.com/172.217.3.206:443]: Connection to upstream server failed java.nio.channels.ClosedChannelException
        at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) ~[browsermob-dist-2.1.2.jar:?]

**Comment by jayantsarda** [comment]
I am facing the same issue while gracefully shutdown:

> [main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server gracefully
[main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (graceful)
[main] INFO org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (graceful)
[LittleProxy-0-ProxyToServerWorker-0] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (CONNECTING) [id: 0x33d5298c]: Connection to upstream server failed
java.nio.channels.ClosedChannelException
	at io.netty.channel.nio.AbstractNioChannel.doClose()(Unknown Source)
[main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server

**Comment by Rajesh-Narayanappa87** [comment]
+1

Same issue for me as well. "Connection to upstream server via chained proxy failed" with selenium 2.53.1, chrome 55, with chained proxies.

**Comment by nikolmarku** [comment]
BMP 2.1.4 and 2.1.2
Complains about some requests, normally it recovers but not for this one
 and then it ends:
[LittleProxy-0-ClientToProxyWorker-4] INFO org.littleshoot.proxy.impl.ClientToProxyConnection - (NEGOTIATING_CONNECT) [id: 0x56a3434d, L:/10.24.208.189:26847 - R:/10.24.208.189:59418]: An IOException occurred on ClientToProxyConnection: An established connection was aborted by the software in your host machine
[LittleProxy-0-ProxyToServerWorker-2] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0xb834c2f9, L:0.0.0.0/0.0.0.0:59419 ! R:efeducationfirstlimi.tt.omtrdc.net/66.235.147.236:443]: Connection to upstream server failed
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
[CodeBlob (0x0000000002801fd0)]
Framesize: 0
BufferBlob (0x0000000002801fd0) used for StubRoutines (2)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:833), pid=65164, tid=73016
#  fatal error: exception happened outside interpreter, nmethods and vtable stubs at pc 0x0000000002804750
#
# JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode windows-amd64 compressed oops)
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\work\project\user

\qa\hs_err_pid65164.log

#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp

**Comment by jayantsarda** [comment]
The Java run time Error is a java 8 bug. I had the same issue and upgrating to latest version of java (jdk1.8.0_121 in my case)  resolves the problem.

Below is the reference of the java bug resolution: https://confluence.atlassian.com/kb/application-crashes-due-to-internal-error-sharedruntime-cpp-833-caused-by-java-8-bug-740098867.html

**Comment by HlebHalkouski** [comment]
@jayantsarda which BMP version did you use? Issue is reproduce on 2.1.2

**Comment by jayantsarda** [comment]
@HiebHalkouski
my BMP version is 2.1.4 and it works perfectly fine on embedded mode. I do see "ProxyToServerConnection" issue in API mode of BMP

**Comment by kiran-z** [comment]
Any updates on this issue?

I have observed this issue with BMP 2.1.4 running in API mode on macOS.

**Comment by HlebHalkouski** [comment]
@kiran-z I start use EC certificates instead of RSA. 
You can enable EC generation in the REST API:

`curl -X POST http://localhost:8080/proxy?useEcc=true`

**Comment by rchougule** [comment]
Hello,
I am facing the same issue. Can somebody please help me debug this?
```
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.chunkSize: 16777216 
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.tinyCacheSize: 512 
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.smallCacheSize: 256 
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.normalCacheSize: 64 
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.maxCachedBufferCapacity: 32768 
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.cacheTrimInterval: 8192 
[DEBUG 2019-09-27T11:52:11,984 io.netty.buffer.PooledByteBufAllocator] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.useCacheForAllThreads: true 
[DEBUG 2019-09-27T11:52:12,005 io.netty.buffer.ByteBufUtil] (qtp1545827753-17 - /proxy) -Dio.netty.allocator.type: pooled 
[DEBUG 2019-09-27T11:52:12,005 io.netty.buffer.ByteBufUtil] (qtp1545827753-17 - /proxy) -Dio.netty.threadLocalDirectBufferSize: 65536 
[DEBUG 2019-09-27T11:52:12,006 io.netty.buffer.ByteBufUtil] (qtp1545827753-17 - /proxy) -Dio.netty.maxThreadLocalCharBufferSize: 16384 
[INFO  2019-09-27T11:52:12,017 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1545827753-17 - /proxy) Proxy started at address: /127.0.0.1:8081 
[DEBUG 2019-09-27T11:52:12,063 org.eclipse.jetty.util.log] (qtp1545827753-17 - /proxy) RESPONSE /proxy  200 
[DEBUG 2019-09-27T11:52:12,069 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) REQUEST /proxy/8081/har on org.eclipse.jetty.server.nio.SelectChannelConnector$2@14db2ada 
[DEBUG 2019-09-27T11:52:12,069 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) sessionManager=org.eclipse.jetty.server.session.HashSessionManager@22356acd 
[DEBUG 2019-09-27T11:52:12,069 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) session=null 
[DEBUG 2019-09-27T11:52:12,069 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) servlet=org.eclipse.jetty.servlet.DefaultServlet-432430300 
[DEBUG 2019-09-27T11:52:12,069 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) servlet holder= 
[DEBUG 2019-09-27T11:52:12,070 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) chain= 
[DEBUG 2019-09-27T11:52:12,070 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) call filter com.google.inject.servlet.GuiceFilter-1209770703 
[DEBUG 2019-09-27T11:52:12,075 org.eclipse.jetty.util.log] (qtp1545827753-15 - /proxy/8081/har) RESPONSE /proxy/8081/har  204 
[DEBUG 2019-09-27T11:52:22,319 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) REQUEST /proxy/8081/har on org.eclipse.jetty.server.nio.SelectChannelConnector$2@1d3dcdec 
[DEBUG 2019-09-27T11:52:22,320 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) sessionManager=org.eclipse.jetty.server.session.HashSessionManager@22356acd 
[DEBUG 2019-09-27T11:52:22,320 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) session=null 
[DEBUG 2019-09-27T11:52:22,320 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) servlet=org.eclipse.jetty.servlet.DefaultServlet-432430300 
[DEBUG 2019-09-27T11:52:22,320 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) servlet holder= 
[DEBUG 2019-09-27T11:52:22,320 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) chain= 
[DEBUG 2019-09-27T11:52:22,321 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) call filter com.google.inject.servlet.GuiceFilter-1209770703 
[DEBUG 2019-09-27T11:52:22,354 org.eclipse.jetty.util.log] (qtp1545827753-20 - /proxy/8081/har) RESPONSE /proxy/8081/har  200 
[DEBUG 2019-09-27T11:52:22,360 org.eclipse.jetty.util.log] (qtp1545827753-16) EOF org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:321) ~[browsermob-dist-2.1.5.jar:?]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214) ~[browsermob-dist-2.1.5.jar:?]
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426) ~[browsermob-dist-2.1.5.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520) [browsermob-dist-2.1.5.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40) [browsermob-dist-2.1.5.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528) [browsermob-dist-2.1.5.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

[INFO  2019-09-27T11:52:22,955 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (LittleProxy-JVM-shutdown-hook) Shutting down proxy server immediately (non-graceful) 
[INFO  2019-09-27T11:52:22,956 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (LittleProxy-JVM-shutdown-hook) Closing all channels (non-graceful) 
```
Any help is appreciated!
Thanks!

**Comment by autumn-develop** [comment]
[LittleProxy-0-ProxyToServerWorker-6] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x2c1336ec, L:/192.168.100.20:52265 ! R:i0001.clarodrive.com/189.247.171.202:443]: Connection to upstream server failed
javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:729)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:684)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:499)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:475)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1387)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:830)
