### ISSUE TITLE
Cannot Add to Blacklist

### ISSUE THREAD

**Issue by MattyC76** [lightbody/browsermob-proxy#525]
**System Setup:**
Ubuntu 16.04
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
browsermob-proxy-2.0.0 and browsermob-proxy-2.1.1
Python browsermob-proxy 0.7.1

**Issue:**
This issue began when I attempted to add websites to a blacklist in Python. I was receiving a 500 HTTP response with the associated message, "Could not initialize class org.mvel2.util.ParseTools." Not a terribly helpful message, so I took a step away from Python and tried the following with the REST API in the Linux shell (using both BMP 2.0.0 and 2.1.1), with https://github.com/lightbody/browsermob-proxy#rest-api as my guide:

**1. sh browsermob-proxy -port 9090**
Result: BMP starts up successfully (expected behavior)

**2. curl -X POST http://localhost:9090/proxy**
Result: Received the message "{"port": 8081}" in Linux shell (expected behavior). NOTE: I also received the following message in the Linux shell, which may or may not have something to do with my problem:

[INFO  2016-08-03T01:14:56,954 io.netty.util.internal.PlatformDependent] (qtp2128961136-41) Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability. 

**3. curl -X GET http://localhost:9090/proxy**
Result: Received the message "{proxyList":[{"port":8081}]}" in Linux shell (expected behavior).

**4. curl -X PUT http://localhost:9090/proxy/8081/blacklist?regex=https?://.*\\facebook\\.com/.*&status=306**  **Note that the markup is gobbling some of my asterisks here. I used the same regex as that specified by your team here: https://github.com/lightbody/browsermob-proxy/commit/30a8978dd87205d25e88853fb33a6517b3e01f20**
Result: Received the following warning in Linux shell:

[WARN  2016-08-03T01:23:51,274 org.eclipse.jetty.util.log] (qtp2128961136-45) Error for /proxy/8082/blacklist java.lang.ExceptionInInitializerError
	at org.mvel2.PropertyAccessor.set(PropertyAccessor.java:249) ~[browsermob-dist-2.1.1.jar:?]
	at org.mvel2.PropertyAccessor.set(PropertyAccessor.java:135) ~[browsermob-dist-2.1.1.jar:?]
	at org.mvel2.MVEL.setProperty(MVEL.java:1088) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.MvelEvaluator.write(MvelEvaluator.java:64) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.binding.MvelRequestBinder.bind(MvelRequestBinder.java:79) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.bindAndReply(WidgetRoutingDispatcher.java:97) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.dispatch(WidgetRoutingDispatcher.java:88) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.DebugModeRoutingDispatcher.dispatch(DebugModeRoutingDispatcher.java:56) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.SitebricksFilter.doFilter(SitebricksFilter.java:62) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.HiddenMethodFilter.doFilter(HiddenMethodFilter.java:70) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) ~[browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323) ~[browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:346) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:592) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528) [browsermob-dist-2.1.1.jar:?]
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "9-i"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(java.base@9-internal/FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(java.base@9-internal/FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(java.base@9-internal/Double.java:539) ~[?:?]
	at org.mvel2.util.ParseTools.<clinit>(ParseTools.java:62) ~[browsermob-dist-2.1.1.jar:?]
	... 35 more

**5. Try the same command again:**
Result: Received the following error in Linux shell (**and the same error I was receiving in Python**):

[WARN  2016-08-03T01:30:45,892 org.eclipse.jetty.util.log] (qtp2128961136-41) Error for /proxy/8081/blacklist java.lang.NoClassDefFoundError: Could not initialize class org.mvel2.util.ParseTools
	at org.mvel2.PropertyAccessor.set(PropertyAccessor.java:249) ~[browsermob-dist-2.1.1.jar:?]
	at org.mvel2.PropertyAccessor.set(PropertyAccessor.java:135) ~[browsermob-dist-2.1.1.jar:?]
	at org.mvel2.MVEL.setProperty(MVEL.java:1088) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.MvelEvaluator.write(MvelEvaluator.java:64) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.binding.MvelRequestBinder.bind(MvelRequestBinder.java:79) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.bindAndReply(WidgetRoutingDispatcher.java:97) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.routing.WidgetRoutingDispatcher.dispatch(WidgetRoutingDispatcher.java:88) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.DebugModeRoutingDispatcher.dispatch(DebugModeRoutingDispatcher.java:56) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.SitebricksFilter.doFilter(SitebricksFilter.java:62) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.sitebricks.HiddenMethodFilter.doFilter(HiddenMethodFilter.java:70) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) ~[browsermob-dist-2.1.1.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) ~[browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323) ~[browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:474) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:935) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:404) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:870) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:346) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:592) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40) [browsermob-dist-2.1.1.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528) [browsermob-dist-2.1.1.jar:?]
	at java.lang.Thread.run(java.base@9-internal/Thread.java:804) [?:?]

**Comment by antonecma** [comment]
@MattyC76 I think you have lost something in  your code code. 
May be here
`4. curl -X PUT http://localhost:9090/proxy/8081/blac...`
I have written a bash [script](https://gist.github.com/antonecma/b5bcbba8db94f55a01eb91d266bc6ac3) to show that the _blacklist_ is working as expected.

**Comment by jekh** [comment]
Since @antonecma pasted a solution and there has been no response, I'll close this issue.
