### ISSUE TITLE
BrowserMobProxyServer effects on firefox data visualization

### ISSUE THREAD

**Issue by KseniaBudlianska** [lightbody/browsermob-proxy#527]
I have project where I run tests on different browsers. Everything is ok when I'm running tests on ChromeDriver. Exactly problem is only for FireFoxDriver. Also I can add that browser shows incorrect interface only at the begining of running. Maybe it's due to heavy ajax, but in general everything was ok before have added a capabilities into FireFoxDriver. You can see on the picture (link: http://prntscr.com/c33s3j) Chrome and FireFox browsers. 

Hope, you will help me with it.
Example of my code (Java):

WebDriver driver = **initDriver(WebDriverEnum.FireFox);**

private WebDriver initDriver(WebDriverEnum browser) {
        switch (browser) {
            case Chrome:
                driver = new ChromeDriver(getCapabilities());
                break;
            **case FireFox:
                getCapabilities().setCapability(FirefoxDriver.PROFILE, getFirefoxDriverProfile());
                driver = new FirefoxDriver(getCapabilities());
                break;**
        }
        return driver;
    }

    private DesiredCapabilities getCapabilities() {
        proxy = new BrowserMobProxyServer();
        proxy.start(0);
        // get the Selenium proxy object
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
        // configure it as a desired capability
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
        return capabilities;
    }

**Comment by jekh** [comment]
Is the problem that the web page isn't rendering correctly when using BMP vs. using straight Firefox? Can you give any more details on the issue? Is there any warning/error information in the log file that might indicate a problem?

**Comment by KseniaBudlianska** [comment]
Sorry for the long delay,

I tried to recreate it again and so, I have the next result: http://prntscr.com/chk07y
I guess somehow BrowserMobProxy doesn't allow to load styles. I will be really appreciate if you help me with all this.

I have the next class:
`public class MobTest {

    private WebDriver driver;
    private BrowserMobProxy proxy;

    public MobTest() {
        driver = initDriver(WebDriverEnum.FireFox);
    }

    @Test
    public void openPage() {
        driver.navigate().to("https://fr.test.languagelogic.net/ascribe/");
        System.out.println("WEB PAGE WAS OPENED");
    }

    private WebDriver initDriver(WebDriverEnum browser) {
        switch (browser) {
            case Chrome:
                driver = new ChromeDriver(getCapabilities());
                break;
            case FireFox:
                getCapabilities().setCapability(FirefoxDriver.PROFILE, getFirefoxDriverProfile());
                driver = new FirefoxDriver(getCapabilities());
                break;
        }
        return driver;
    }

    private DesiredCapabilities getCapabilities() {
        proxy = new BrowserMobProxyServer();
        proxy.start(0);
        // get the Selenium proxy object
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
        // configure it as a desired capability
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
        return capabilities;
    }

    private FirefoxProfile getFirefoxDriverProfile() {
        FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference("browser.download.folderList", 2);
        profile.setPreference("browser.download.manager.showWhenStarting", false);
        profile.setPreference("browser.download.dir", getDownloadDir().getAbsoluteFile().getAbsolutePath());
        profile.setPreference("browser.helperApps.neverAsk.saveToDisk",
                "image/jpeg, application/xlsx, application/zip, application/msword, text/xml, application/octet-stream");
        return profile;
    }

    public File getDownloadDir() {
        File folder = new File(System.getProperty("user.dir") + FileUtil.getResourcesDir() + "files/");
        folder.mkdir();
        return folder;
    }
}`

**During running FireFox browser I got the next log:**

2016-09-13 18:03:31,885 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2016-09-13 18:03:31,922 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
2016-09-13 18:03:31,982 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:52681
2016-09-13 18:03:32,038 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2016-09-13 18:03:32,046 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
2016-09-13 18:03:32,047 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:52718
WEB PAGE WAS OPENED
2016-09-13 18:03:43,878 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
2016-09-13 18:03:43,878 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
2016-09-13 18:03:43,879 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
2016-09-13 18:03:43,879 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
2016-09-13 18:03:43,892 LittleProxy-1-ProxyToServerWorker-1 [INFO ] org.littleshoot.proxy.impl.ProxyToServerConnection - (CONNECTING) [id: 0x22902c0a]: Connection to upstream server failed
java.nio.channels.ClosedChannelException
	at io.netty.channel.nio.AbstractNioChannel.doClose()(Unknown Source)
2016-09-13 18:03:43,893 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
2016-09-13 18:03:43,897 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server
2016-09-13 18:03:43,893 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
2016-09-13 18:03:43,900 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server
2016-09-13 18:03:43,933 LittleProxy-1-ClientToProxyWorker-1 [WARN ] io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xeee59f90]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:800)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:743)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:422)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:72)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
	at org.littleshoot.proxy.impl.ProxyToServerConnection$1.execute(ProxyToServerConnection.java:650)
	at org.littleshoot.proxy.impl.ConnectionFlow.doProcessCurrentStep(ConnectionFlow.java:140)
	at org.littleshoot.proxy.impl.ConnectionFlow.processCurrentStep(ConnectionFlow.java:128)
	at org.littleshoot.proxy.impl.ConnectionFlow.advance(ConnectionFlow.java:90)
	at org.littleshoot.proxy.impl.ConnectionFlow.start(ConnectionFlow.java:76)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.connectAndWrite(ProxyToServerConnection.java:551)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.write(ProxyToServerConnection.java:322)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.write(ProxyToServerConnection.java:308)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:336)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:192)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:81)
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135)
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120)
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)
2016-09-13 18:03:43,947 LittleProxy-1-ClientToProxyWorker-1 [ERROR] io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:800)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:345)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:743)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1008)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:433)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:72)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
	at org.littleshoot.proxy.impl.ProxyToServerConnection$1.execute(ProxyToServerConnection.java:650)
	at org.littleshoot.proxy.impl.ConnectionFlow.doProcessCurrentStep(ConnectionFlow.java:140)
	at org.littleshoot.proxy.impl.ConnectionFlow.processCurrentStep(ConnectionFlow.java:128)
	at org.littleshoot.proxy.impl.ConnectionFlow.advance(ConnectionFlow.java:90)
	at org.littleshoot.proxy.impl.ConnectionFlow.start(ConnectionFlow.java:76)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.connectAndWrite(ProxyToServerConnection.java:551)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.write(ProxyToServerConnection.java:322)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.write(ProxyToServerConnection.java:308)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:336)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:192)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:81)
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135)
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120)
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel
Process finished with exit code 0

**During running Chrome browser:**
2016-09-13 18:12:06,907 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2016-09-13 18:12:06,940 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
2016-09-13 18:12:07,000 main [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:53130
Starting ChromeDriver (v2.8.241075) on port 24789
WEB PAGE WAS OPENED
2016-09-13 18:12:20,297 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Shutting down proxy server immediately (non-graceful)
2016-09-13 18:12:20,297 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Closing all channels (non-graceful)
2016-09-13 18:12:20,316 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.ServerGroup - Shutting down server group event loops (non-graceful)
2016-09-13 18:12:20,321 LittleProxy-JVM-shutdown-hook [INFO ] org.littleshoot.proxy.impl.DefaultHttpProxyServer - Done shutting down proxy server

Process finished with exit code 0
