### ISSUE TITLE
Error: browsermob-proxy.pid undefined

### ISSUE THREAD

**Issue by macroking** [lightbody/browsermob-proxy#547]
Unable to start browsermob-manager

$ ./node_modules/.bin/browsermob-manager start --port 8080
browsermob-proxy.pid: undefined
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\TKing\playground\PerformanceMonitor\node_modules\browsermob\bin\browsermob-proxy-2.1.2\bin\browsermob-proxy ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

Additional Info:
nodejs version: v4.2.4
npm version : 2.14.12
browermob pakage version: 0.0.2
browermob-proxy version: 2.1.2

**Comment by jekh** [comment]
It looks like you're running BMP via node. You might want to report the issue with the BMP+Node project: https://github.com/zzo/browsermob-node
