### ISSUE TITLE
Caught an exception on ClientT oProxyConnection io.netty.handler.codec.DecoderException: javax.net.ssl.SSLExcep tion: Received fatal alert: unknown_ca

### ISSUE THREAD

**Issue by kevaldsoni** [lightbody/browsermob-proxy#560]
Browser mob proxy - 2.1.2
Python - 2.7

Running proxy to capture http and https request

0:0:0:0:0:0:0:1:8081 - R:/0:0:0:0:0:0:0:1:61379]: Caught an exception on ClientT
oProxyConnection io.netty.handler.codec.DecoderException: javax.net.ssl.SSLExcep
tion: Received fatal alert: unknown_ca
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageD
ecoder.java:442) ~[browsermob-dist-2.1.2.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessage
Decoder.java:248) ~[browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Abstra
ctChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Defau
ltChannelPipeline.java:1334) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abst
ractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChanne
lPipeline.java:926) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:123) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:571) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:512) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
va:426) [browsermob-dist-2.1.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) [browser
mob-dist-2.1.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
EventExecutor.java:877) [browsermob-dist-2.1.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca

Code 
from browsermobproxy import Server
from selenium import webdriver
import json

server = Server("browsermob-proxy")
server.start()
proxy = server.create_proxy()
profile = webdriver.FirefoxProfile()
profile.set_proxy(proxy.selenium_proxy())
driver = webdriver.Firefox(firefox_profile=profile)
proxy.new_har("http://stackoverflow.com", options={'captureHeaders': True})
driver.get("http://stackoverflow.com")    
result = json.dumps(proxy.har, ensure_ascii=False)
print result
proxy.stop()    
driver.quit()

**Comment by antonecma** [comment]
Just use **trustAllServers** option, when you start new proxy instance.

**Comment by kevaldsoni** [comment]
proxy.trustAllServers(True)
AttributeError: 'Client' object has no attribute 'trustAllServers'

Browser mob proxy version used is 2.1.2

**Comment by kevaldsoni** [comment]
Added code python code : proxy.trustAllServers(True)

Error obtained : AttributeError: 'Client' object has no attribute 'trustAllServers'

Kindly check if it is the correct way to add attribute to proxy also Browser mob proxy version used is 2.1.2

Thanks

**Comment by antonecma** [comment]
So, I am think that a trouble in your python module, which not realize **trustAllServers** option.

**Comment by jekh** [comment]
Yes, @antonecma is exactly right, the python binding may not expose the setTrustAllServers option. You can find more information on the python binding at that project: https://github.com/AutomatedTester/browsermob-proxy-py
