### ISSUE TITLE
Can't use https proxy for webdriver on Tomcat

### ISSUE THREAD

**Issue by hufeiya** [lightbody/browsermob-proxy#564]
Hi there
I can use https proxy in local environment with the IE webdriver  by just copying the readme code and add the .cer.But when I deploy the same code on tomcat,the webdriver can't view https sites.

`15:28:26.444 [LittleProxy-0-ClientToProxyWorker-3] DEBUG o.l.p.impl.ProxyToServerConnection - (DISCONNECTED): Currently disconnected, connect and then write the message
15:28:26.444 [LittleProxy-0-ClientToProxyWorker-3] DEBUG o.l.p.impl.ProxyToServerConnection - (DISCONNECTED): Starting new connection to: www.baidu.com/115.239.211.112:443
15:28:26.444 [LittleProxy-0-ClientToProxyWorker-3] WARN  net.lightbody.bmp.mitm.util.SslUtil - Disabling upstream server certificate verification. This will allow attackers to intercept communications with upstream servers.
15:28:26.476 [LittleProxy-0-ClientToProxyWorker-3] ERROR o.l.p.impl.ClientToProxyConnection - (AWAITING_INITIAL) [id: 0x12da5951, L:/192.168.1.154:51857 - R:/192.168.1.154:52389]: Caught an exception on ClientToProxyConnection
java.lang.NoClassDefFoundError: org/apache/tomcat/jni/CertificateRequestedCallback
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:749) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:395) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
	at net.lightbody.bmp.mitm.util.SslUtil.getUpstreamServerSslContext(SslUtil.java:95) ~[mitm-2.1.2.jar:na]
	at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager$1.get(ImpersonatingMitmManager.java:74) ~[mitm-2.1.2.jar:na]
	at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager$1.get(ImpersonatingMitmManager.java:1) ~[mitm-2.1.2.jar:na]
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:131) ~[guava-19.0.jar:na]
	at net.lightbody.bmp.mitm.manager.ImpersonatingMitmManager.serverSslEngine(ImpersonatingMitmManager.java:205) ~[mitm-2.1.2.jar:na]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.initializeConnectionFlow(ProxyToServerConnection.java:592) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.connectAndWrite(ProxyToServerConnection.java:550) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.write(ProxyToServerConnection.java:322) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.write(ProxyToServerConnection.java:308) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.doReadHTTPInitial(ClientToProxyConnection.java:336) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:192) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.readHTTPInitial(ClientToProxyConnection.java:81) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) ~[littleproxy-1.1.0-beta-bmp-13.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$RequestReadMonitor.channelRead(ProxyConnection.java:715) [littleproxy-1.1.0-beta-bmp-13.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) [littleproxy-1.1.0-beta-bmp-13.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.39.Final.jar:4.0.39.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.jni.CertificateRequestedCallback
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285) ~[catalina.jar:8.5.8]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ~[catalina.jar:8.5.8]
	... 51 common frames omitted
`

**Comment by hufeiya** [comment]
sorry，perhaps I need to install the cer on tomcat

**Comment by hufeiya** [comment]
Perhaps it's the tomcat's problem.When I switch to jetty,it works fine.

**Comment by jekh** [comment]
This does appear to be tomcat-specific. The stack trace shows:
`Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.jni.CertificateRequestedCallback`

I'm not sure what tomcat is doing to interfere with Netty's SslContextBuilder there. I don't use tomcat so I don't know any details, but if you are still having the issue and can dig up some more information, feel free to reopen.
