### ISSUE TITLE
Show help message when unknown command line flags provided

### ISSUE THREAD

**Issue by lexrj** [lightbody/browsermob-proxy#566]
Currently browsermob-proxy just throws an error when presented with an unknown argument (such as --version), obscuring the issue slightly. It would be cleaner to have it take any unknown argument as a call for the help message.

```
Nov 29, 2016 5:20:18 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: joptsimple.UnrecognizedOptionException: 'v' is not a recognized option
joptsimple.UnrecognizedOptionException: 'v' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:93)
	at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:470)
	at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:420)
	at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:415)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:57)
	at joptsimple.OptionParser.parse(OptionParser.java:392)
	at net.lightbody.bmp.proxy.guice.ConfigModule.configure(ConfigModule.java:57)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.lightbody.bmp.proxy.Main.main(Main.java:42)

Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=port) was bound.
  while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=port)
    for parameter 0 at net.lightbody.bmp.proxy.guice.JettyServerProvider.<init>(JettyServerProvider.java:19)
  at net.lightbody.bmp.proxy.guice.JettyModule.configure(JettyModule.java:10)

2) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=address) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=address)
    for parameter 1 at net.lightbody.bmp.proxy.guice.JettyServerProvider.<init>(JettyServerProvider.java:19)
  at net.lightbody.bmp.proxy.guice.JettyModule.configure(JettyModule.java:10)

3) An exception was caught and reported. Message: 'v' is not a recognized option
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.lightbody.bmp.proxy.Main.main(Main.java:42)
Caused by: joptsimple.UnrecognizedOptionException: 'v' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:93)
	at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:470)
	at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:420)
	at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:415)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:57)
	at joptsimple.OptionParser.parse(OptionParser.java:392)
	at net.lightbody.bmp.proxy.guice.ConfigModule.configure(ConfigModule.java:57)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 4 more
```

**Comment by jekh** [comment]
Yes, completely agree, the current behavior is not good. I'm (still) working on the new REST API, and it will include a much better support for command-line options. I'm not planning to modify the existing `Main` class before the REST API update is complete, but please do feel free to submit a PR if you'd like this to go in before the next major version update.
