### ISSUE TITLE
ssl handshake exception while using browsermob-core 2.1.4

### ISSUE THREAD

**Issue by jagdish-sp** [lightbody/browsermob-proxy#591]
Hi,
I am getting the below error after the browser launches.

javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source)
	at javax.net.ssl.SSLEngine.unwrap(Unknown Source)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker$1.run(Unknown Source)
	at sun.security.ssl.Handshaker$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Unknown Source)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1123)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1008)
	... 17 more

 I had lot of dependency issues with duplicate classes error, so resolved these issues by excluding these duplicate classes in different jars.

Now my browsermob-core dependency looks like this:

    <dependency>
        <groupId>net.lightbody.bmp</groupId>
        <artifactId>browsermob-core</artifactId>
        <version>2.1.4</version>
        <scope>test</scope>
        	<exclusions>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcprov-jdk15on</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcpkix-jdk15on</artifactId>
				</exclusion>

				<exclusion>
    				<groupId>com.google.guava</groupId>
    				<artifactId>guava</artifactId>
				</exclusion>

					<exclusion>
   					<groupId>org.slf4j</groupId>
   					<artifactId>jcl-over-slf4j</artifactId>
					</exclusion>
					<exclusion>
    				<groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
				</exclusion>
	        </exclusions>			
    </dependency>

<dependency>
 <groupId>net.lightbody.bmp</groupId>
    <artifactId>littleproxy</artifactId>
        <version>1.1.0-beta-bmp-15</version>
    
    	    		<exclusions>
    
				<exclusion>
    				<groupId>com.google.guava</groupId>
    				<artifactId>guava</artifactId>
				</exclusion>
				
								</exclusions>
				
</dependency>

		<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>19.0</version>
</dependency>

I also looked at this issue https://github.com/lightbody/browsermob-proxy/issues/437
but, I dont get settrustallservers option for my BrowserMobProxyServer object nor the selenium Proxy object.

Can you please let me know, what I am missing here.

Thanks & Regards
Jagdish

**Comment by jagdish-sp** [comment]
I am using selenium 2.45.0

**Comment by jekh** [comment]
It looks like you haven't pasted the full stack trace, so I can't tell what the SSL exception was, but it's most likely that whatever internal system(s) you're connecting to do not have certificates signed by a public CA. There are a few ways to resolve this problem, one of which is to use the setTrustAllServers() method on the BrowserMobProxy object. See the javadocs on that method for details.

I'd also recommend you use a more recent version of selenium; 2.45.0 is quite old.

**Comment by jekh** [comment]
Since there's been no update, I'll close this issue for now.
