### ISSUE TITLE
Unable replace Response status using REST API

### ISSUE THREAD

**Issue by Balinski** [lightbody/browsermob-proxy#594]
I'm trying change response status to 503:
HttpPost request = new HttpPost(http://myHost.MyCompany.com:9090/proxy/8083/filter/response);
StringEntity entityString = new StringEntity("if (messageInfo.getUrl().contains('usage')) {response.setStatus(HttpResponseStatus.SERVICE_UNAVAILABLE);}");
request.setEntity(entityString);
// Execute request
CloseableHttpResponse response = executeRequest(request);

but in proxy log i receive error:

[ERROR 2017-01-10T09:08:16,435 net.lightbody.bmp.filters.JavascriptRequestResponseFilter] (LittleProxy-3-ProxyToServerWorker-0) Could not invoke filterResponse using supplied javascript javax.script.ScriptException: ReferenceError: "HttpResponseStatus" is not defined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:423) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:73) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:511) ~[nashorn.jar:?]
	at javax.script.CompiledScript.eval(CompiledScript.java:92) ~[?:1.8.0_111]
	at net.lightbody.bmp.filters.JavascriptRequestResponseFilter.filterResponse(JavascriptRequestResponseFilter.java:86) [browsermob-dist-2.1.2.jar:?]
	at net.lightbody.bmp.filters.ResponseFilterAdapter.serverToProxyResponse(ResponseFilterAdapter.java:49) [browsermob-dist-2.1.2.jar:?]
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.serverToProxyResponse(BrowserMobHttpFilterChain.java:123) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ClientToProxyConnection.respond(ClientToProxyConnection.java:419) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.respondWith(ProxyToServerConnection.java:536) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.readHTTPInitial(ProxyToServerConnection.java:229) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.readHTTPInitial(ProxyToServerConnection.java:75) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyToServerConnection.read(ProxyToServerConnection.java:218) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection$ResponseReadMonitor.channelRead(ProxyConnection.java:738) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [browsermob-dist-2.1.2.jar:?]
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) [browsermob-dist-2.1.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [browsermob-dist-2.1.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "HttpResponseStatus" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291) ~[nashorn.jar:?]
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1426) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:1) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:418) ~[nashorn.jar:?]
	... 63 more

If I try replace header, it's ok
"if (messageInfo.getUrl().contains('usage')) {response.headers().remove('Server'); response.headers().add('Server', 'FM');}"

**Comment by jekh** [comment]
The error is right at the top of your stack trace. Why don't you just use a literal 503? If you really want to use the constant, consult the Nashorn docs for information on properly referencing Java classes from Nashon javascript.

**Comment by Balinski** [comment]
when i use literal 503 - {response.setStatus(503);} 

[WARN  2017-01-10T11:44:16,712 net.lightbody.bmp.filters.BrowserMobHttpFilterChain] (LittleProxy-7-ProxyToServerWorker-0) Filter in filter chain threw exception. Filter method may have been aborted. java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(FullHttpResponse,HttpResponseStatus)FullHttpResponse to (Object,int)Object

**Comment by Balinski** [comment]
I find solution:
"if (messageInfo.getUrl().contains('usage')) {var Status = Java.type('io.netty.handler.codec.http.HttpResponseStatus'); response.setStatus(Status.SERVICE_UNAVAILABLE);}"
