### ISSUE TITLE
Unable to filter images

### ISSUE THREAD

**Issue by cambiph** [lightbody/browsermob-proxy#600]
Hello,

I am trying to filter images out from my webdriver tests. However I cannot seem to get it working.
This is the logging I get when the filtering is enabled:

```
2017-02-01 13:00:10 INFO  DefaultHttpProxyServer:485 - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2017-02-01 13:00:10 INFO  DefaultHttpProxyServer:514 - Proxy listening with TCP transport
2017-02-01 13:00:10 INFO  DefaultHttpProxyServer:549 - Proxy started at address: /0:0:0:0:0:0:0:0:52072
2017-02-01 13:00:10 INFO  ChromeBrowser:51 - RemoteWebDriver not set yet, I'll build and start it for you.
2017-02-01 13:00:10 INFO  ChromeBrowser:28 - Building ChromeDriver service ...
2017-02-01 13:00:10 INFO  ChromeBrowser:41 - Starting ChromeDriver service ...
Starting ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9) on port 23255
Only local connections are allowed.
feb 01, 2017 1:00:10 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
feb 01, 2017 1:00:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
[301.973][SEVERE]: Timed out receiving message from renderer: 298.892
[301.978][SEVERE]: Timed out receiving message from renderer: -0.005
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xadb73753, L:/10.121.10.51:52072 - R:/10.121.10.51:52156]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x0a7b4736, L:/10.121.10.51:52072 - R:/10.121.10.51:52117]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xe8d4be72, L:/10.121.10.51:52072 - R:/10.121.10.51:52131]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xe3f5c1e6, L:/10.121.10.51:52072 - R:/10.121.10.51:52112]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xfb514d46, L:/10.121.10.51:52072 - R:/10.121.10.51:52141]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xbf6f6db2, L:/10.121.10.51:52072 - R:/10.121.10.51:52146]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x6c7afd04, L:/10.121.10.51:52072 - R:/10.121.10.51:52119]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x4723b07f, L:/10.121.10.51:52072 - R:/10.121.10.51:52094]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xdb5d3ca1, L:/10.121.10.51:52072 - R:/10.121.10.51:52095]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xabdf8f32, L:/10.121.10.51:52072 - R:/10.121.10.51:52097]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x7a57161a, L:/10.121.10.51:52072 - R:/10.121.10.51:52090]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x0435905a, L:/10.121.10.51:52072 - R:/10.121.10.51:52138]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xdc3e9e44, L:/10.121.10.51:52072 - R:/10.121.10.51:52084]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x3a594049, L:/10.121.10.51:52072 - R:/10.121.10.51:52096]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x800307b4, L:/10.121.10.51:52072 - R:/10.121.10.51:52087]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xd3b99c21, L:/10.121.10.51:52072 - R:/10.121.10.51:52092]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x40bafad5, L:/10.121.10.51:52072 - R:/10.121.10.51:52101]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x400c4eed, L:/10.121.10.51:52072 - R:/10.121.10.51:52199]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x1fe68879, L:/10.121.10.51:52072 - R:/10.121.10.51:52122]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x8634dc0f, L:/10.121.10.51:52072 - R:/10.121.10.51:52113]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xc831c75e, L:/10.121.10.51:52072 - R:/10.121.10.51:52118]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x050de4ec, L:/10.121.10.51:52072 - R:/10.121.10.51:52150]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xad31e1fd, L:/10.121.10.51:52072 - R:/10.121.10.51:52120]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x426dce4a, L:/10.121.10.51:52072 - R:/10.121.10.51:52130]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xe9b8e40c, L:/10.121.10.51:52072 - R:/10.121.10.51:52116]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xf394a65a, L:/10.121.10.51:52072 - R:/10.121.10.51:52140]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xe9fc002e, L:/10.121.10.51:52072 - R:/10.121.10.51:52133]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0xbf783c77, L:/10.121.10.51:52072 - R:/10.121.10.51:52121]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken
2017-02-01 13:05:12 INFO  ClientToProxyConnection:729 - (AWAITING_INITIAL) [id: 0x42aad02a, L:/10.121.10.51:52072 - R:/10.121.10.51:52144]: An IOException occurred on ClientToProxyConnection: De externe host heeft een verbinding verbroken

org.openqa.selenium.TimeoutException: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -0.005
  (Session info: chrome=55.0.2883.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 300.01 seconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'DESKTOP-5HVN7JC', ip: '10.121.10.51', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=C:\Users\Philippe\AppData\Local\Temp\scoped_dir23212_6924}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: a09bc00e6bf76cd28ca544dcc371ed8b

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
	at ChromeTest.test(ChromeTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

2017-02-01 13:05:12 INFO  DefaultHttpProxyServer:426 - Shutting down proxy server immediately (non-graceful)
2017-02-01 13:05:12 INFO  DefaultHttpProxyServer:459 - Closing all channels (non-graceful)
2017-02-01 13:05:12 INFO  ServerGroup:212 - Shutting down server group event loops (non-graceful)
2017-02-01 13:05:12 INFO  DefaultHttpProxyServer:440 - Done shutting down proxy server

Process finished with exit code -1
```

What I try to accomplish is that when a request for a png is sent through the proxy, the request immediately sends back a 404 so it doesn't try to fetch it. This is to increase the speed of the webdriver tests. However, the initial page seems to open and just keeps on loading. After 5min I get above stacktrace.
The code can be found here: https://github.com/cambiph/selenium-3

**Comment by cambiph** [comment]
Seem to have solved it myself. Instead of telling the proxy to return a 404, I set it to a 200. Now it seems to work.
