### ISSUE TITLE
Unable to capture HTTPS Network Traffic from Mobile app (Embedded Mode)

### ISSUE THREAD

**Issue by Joshli2017** [lightbody/browsermob-proxy#607]
Hi,
I am able to capture HTTPS traffic from any Android phone browser but when I am trying to capture HTTPS traffic from the app it shows Unable to connect to server as response. Is there anything I need to add as capabilities in order to capture HTTPS traffic from app? I can capture all HTTP traffic with proper response.

I am using browser mob (2.1.4), appium (v 1.4.16.1 Ophiuchus) and Android v 6.0.1)

**Comment by jekh** [comment]
Have you installed the CA certificate into the phone's trust store? Are there any error messages in the BMP logs?

**Comment by Joshli2017** [comment]
Hi @jekh 
I am using following command which installs LiitleProxy RSA Impersonation CA on Android mobile device. 
BrowserMobProxy BMPproxy=new BrowserMobProxyServer();
BMPproxy.setMitmManager(ImpersonatingMitmManager.builder().trustAllServers(true).build());

for all Https request from the app I am getting following logs:
[LittleProxy-0-ProxyToServerWorker-6] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x0ba4e0a9, L:0.0.0.0/0.0.0.0:52808 ! R:xyzdns.net/172.217.25.34:443]: Connection to upstream server failed
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

Based on the other such issue raised, I did checked SSL support section, but couldnt figure it out what needs to be done in order to capture HTTPS from app as from the browser on Android phone its able to capture all https request/response.

**Comment by Joshli2017** [comment]
Here is the detail error log if it helps.

[LittleProxy-0-ProxyToServerWorker-6] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x0ba4e0a9, L:0.0.0.0/0.0.0.0:52808 ! R:xyzdns.net/172.217.25.34:443]: Connection to upstream server failed
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)
[LittleProxy-0-ClientToProxyWorker-7] ERROR org.littleshoot.proxy.impl.ClientToProxyConnection - (AWAITING_INITIAL) [id: 0x01be02f1, L:0.0.0.0/0.0.0.0:8888 ! R:/10.1.0.83:55870]: Caught an exception on ClientToProxyConnection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 15 more

**Comment by jekh** [comment]
BMP is throwing this exception because the certificate for `xyzdns.net` is not signed by a known CA. The problem is actually occurring in the proxy->server connection rather than browser->proxy connection. Looking at the cert for xyzdns.net, it's not only untrusted, it's also invalid (no SAN matching xyzdns.net).

If you control xyzdns.net, I'd install a valid cert on it. Preferably one that's signed by a known CA, but even an untrusted cert would be fine, as long as it's valid.

You could use the `.setTrustAllServers()` method to disable upstream certificate validation, though I can't recommend that approach in general since it would allow your requests to be intercepted. In this case, however, there really isn't another way to connect to xyzdns.net, since it's not currently possible to tell BMP to accept an invalid (as opposed to untrusted) certificate.

**Comment by Joshli2017** [comment]
Thanks for the advice. I obfuscated the DNS entry when I posted, see the end for a unedited file. I have tried the following:

- Using setTrustAllServers(true) - No change
- Using setTrustSource(null) - which is how setTrustAllServers works under the hood - no changes.

I find it strange that the proxy server doesn't trust google's HTTPS certificates by default (see the dns name being looked up below). Is it possible this is a bug in the software?

`[LittleProxy-0-ClientToProxyWorker-5] ERROR org.littleshoot.proxy.impl.ClientToProxyConnection - (NEGOTIATING_CONNECT) [id: 0xea6f0c4a, L:0.0.0.0/0.0.0.0:8888 ! R:/10.1.0.83:53903]: Caught an exception on ClientToProxyConnection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
[LittleProxy-0-ProxyToServerWorker-6] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x819b58c7, L:0.0.0.0/0.0.0.0:60684 ! R:pubads.g.doubleclick.net/216.58.199.34:443]: Connection to upstream server failed
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)[LittleProxy-0-ClientToProxyWorker-6] ERROR org.littleshoot.proxy.impl.ClientToProxyConnection - (NEGOTIATING_CONNECT) [id: 0x6a39ef72, L:0.0.0.0/0.0.0.0:8888 ! R:/10.1.0.83:39546]: Caught an exception on ClientToProxyConnection

	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
`

**Comment by jekh** [comment]
The second stacktrace shows that the issue is occuring on the ClientToProxyConnection:
```
[LittleProxy-0-ClientToProxyWorker-5] ERROR org.littleshoot.proxy.impl.ClientToProxyConnection - (NEGOTIATING_CONNECT) [id: 0xea6f0c4a, L:0.0.0.0/0.0.0.0:8888 ! R:/10.1.0.83:53903]: Caught an exception on ClientToProxyConnection io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown 
```

The client (the Android device) needs to trust the CA that BMP uses to sign the impersonated certificates. You'll need to consult the Android docs for adding a new CA to Android/Chrome's trust store. (It cannot be done with Java code, and it cannot be done from the proxy.)

BMP uses the latest Mozilla truststore, so it definitely trusts Google's CA.

**Comment by Joshli2017** [comment]
Thanks @jekh.
