### ISSUE TITLE
The connection is not disconnected after the BMP is stopped

### ISSUE THREAD

**Issue by zhiying8710** [lightbody/browsermob-proxy#628]
I run selenium application on xp, and use BMP to proxy ie, because `LittleProxy` reuse `ProxyToServerConnection`, so can not dynamic change the chained proxy to same server, but I dont want to start a new ie. so I will restart BMP(stop a BMP and use the it's port to start, so dont need to restart ie), But my application runs about four hours later, throws exception:
`java.net.SocketException: No buffer space available (maximum connections reached?): listen
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketException: No buffer space available (maximum connections reached?): listen
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:202)
	at com.cardniu.bank.crawl.manage.CrawlerManager.waitForGenerating(CrawlerManager.java:294)
	at com.cardniu.bank.crawl.manage.CrawlerManager.access$900(CrawlerManager.java:48)
	at com.cardniu.bank.crawl.manage.CrawlerManager$4.run(CrawlerManager.java:281)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: java.net.SocketException: No buffer space available (maximum connections reached?): listen
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer.doStart(DefaultHttpProxyServer.java:524)
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer.start(DefaultHttpProxyServer.java:465)
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer.access$700(DefaultHttpProxyServer.java:72)
	at org.littleshoot.proxy.impl.DefaultHttpProxyServer$DefaultHttpProxyServerBootstrap.start(DefaultHttpProxyServer.java:805)
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:360)
	at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:370)
	at com.cardniu.bank.crawl.worker.proxy.BrowserMobProxyServerUtils.create(BrowserMobProxyServerUtils.java:37)
	at com.cardniu.bank.crawl.manage.DriverGeneCallable.mobProxy(DriverGeneCallable.java:242)
	at com.cardniu.bank.crawl.manage.DriverGeneCallable.call(DriverGeneCallable.java:72)
	at com.cardniu.bank.crawl.manage.DriverGeneCallable.call(DriverGeneCallable.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	... 3 more
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): listen
	at sun.nio.ch.Net.listen(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:215)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:498)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:413)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:399)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:349)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	... 1 more`

and use I found plenty tcp connections:

![1](https://cloud.githubusercontent.com/assets/3991089/25275308/2b788a1e-26c7-11e7-8aac-1d90617d561a.png)
![2](https://cloud.githubusercontent.com/assets/3991089/25275310/2f72af6e-26c7-11e7-935c-6257d645b74f.png)

**Comment by pro4jhu** [comment]
i have the same problem, did you solve now?
