### ISSUE TITLE
Connection to upstream server failed javax.net.ssl.SSLHandshakeException: General SSLEngine problem

### ISSUE THREAD

**Issue by swathirao87** [lightbody/browsermob-proxy#642]
I am getting this error(In browsermob-proxy) while trying to launch chrome for one of my test case using NPM. Getting the below mentioned error.

Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Running BrowserMob Proxy using LittleProxy implementation. To revert to the legacy implementation, run the proxy with the command-line option '--use-littleproxy false'.
[INFO  2017-05-31T16:05:36,218 net.lightbody.bmp.proxy.Main] (main) Starting BrowserMob Proxy version 2.1.4
[INFO  2017-05-31T16:05:36,265 org.eclipse.jetty.util.log] (main) jetty-7.x.y-SNAPSHOT
[INFO  2017-05-31T16:05:36,437 org.eclipse.jetty.util.log] (main) started o.e.j.s.ServletContextHandler{/,null}
[INFO  2017-05-31T16:05:36,687 org.eclipse.jetty.util.log] (main) Started SelectChannelConnector@0.0.0.0:8080
[INFO  2017-05-31T16:06:26,092 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp13538920-16) Starting proxy at address: 0.0.0.0/0.0.0.0:8888
[INFO  2017-05-31T16:06:26,170 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp13538920-16) Proxy listening with TCP transport
[INFO  2017-05-31T16:06:26,420 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp13538920-16) Proxy started at address: /0.0.0.0:8888
[INFO  2017-05-31T16:06:27,428 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-0-ProxyToServerWorker-1) (HANDSHAKING) [id: 0x7f13652e, L:0.0.0.0/0.0.0.0:65092 ! R:arcwebdev01.amr.corp.intel.com/10.11.44.25
4:1338]: Connection to upstream server failed javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Unknown Source) ~[?:1.8.0_131]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source) ~[?:1.8.0_131]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[?:1.8.0_131]
        at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[?:1.8.0_131]
        at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[?:1.8.0_131]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097) [browsermob-dist-2.1.4.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968) [browsermob-dist-2.1.4.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) [browsermob-dist-2.1.4.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [browsermob-dist-2.1.4.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [browsermob-dist-2.1.4.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [browsermob-dist-2.1.4.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [browsermob-dist-2.1.4.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by jekh** [comment]
It looks like the server you're trying to connect to is throwing an error during the handshake.
