### ISSUE TITLE
BrowserMobProxy v2.1.4, getting SSLException: Received fatal alert: unknown_ca

### ISSUE THREAD

**Issue by egloffmark** [lightbody/browsermob-proxy#656]
Dear all I try to setup my Selenium Test with the FirefoxDriver and the BrowserMobProxy (v2.1.4). When I try to access a https protected page I receive the following exception. 

    javax.net.ssl.SSLException: Received fatal alert: unknown_ca

I tried already to configure the proxy and the driver to accept all certificates, but this did not help.

 - proxy.setTrustAllServers(true)
 - myprofile.setAcceptUntrustedCertificates(true)
 - myprofile.setAssumeUntrustedCertificateIssuer(false);

Any suggestions what can be tried to fix this? 

**My Java code**

    // setup proxy
    BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.setTrustAllServers(true);
        
    ProxyLogger filter = new ProxyLogger();
    proxy.addRequestFilter(filter);
    proxy.addResponseFilter(filter);

    proxy.start();
 		
    ProfilesIni profile = new ProfilesIni();
    FirefoxProfile myprofile = profile.getProfile("default");
    myprofile.setAcceptUntrustedCertificates(true);

    myprofile.setPreference("network.proxy.type", 1);
    myprofile.setPreference("network.proxy.http", "localhost");
    myprofile.setPreference("network.proxy.http_port", proxy.getPort());
    myprofile.setPreference("network.proxy.ssl", "localhost");
    myprofile.setPreference("network.proxy.ssl_port", proxy.getPort());
		
    FirefoxDriver driver = new FirefoxDriver(myprofile);

    driver.get("https://www.google.com");

**Full Output with Stacktrace of the Exception** while accessing https://www.google.com

    2017-06-16 19:20:44 INFO  DefaultHttpProxyServer:485 - Starting proxy at address: 0.0.0.0/0.0.0.0:0
    2017-06-16 19:20:44 INFO  DefaultHttpProxyServer:514 - Proxy listening with TCP transport
    2017-06-16 19:20:44 INFO  DefaultHttpProxyServer:549 - Proxy started at address: /0:0:0:0:0:0:0:0:45125
    2017-06-16 19:20:46 INFO  ProxyLogger:20 - >>> REQUEST  uri=tiles.services.mozilla.com:443, method=CONNECT
    2017-06-16 19:20:46 WARN  SslUtil:85 - Disabling upstream server certificate verification. This will allow attackers to intercept communications with upstream servers.
    2017-06-16 19:20:48 INFO  ProxyLogger:20 - >>> REQUEST  uri=www.google.ch:443, method=CONNECT
    2017-06-16 19:20:49 INFO  RootCertificateGenerator:113 - Generated CA root certificate and private key in 887ms. Key generator: RSA (2048). Signature algorithm: SHA384.
    2017-06-16 19:20:49 ERROR ClientToProxyConnection:735 - (AWAITING_INITIAL) [id: 0x3c0e3e53, L:/127.0.0.1:45125 - R:/127.0.0.1:42110]: Caught an exception on ClientToProxyConnection
    io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:748)
    Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 15 more

**Comment by egloffmark** [comment]
I also tried with the standalone version of BrowserMobProxy and configured my normal Firefox Browser to use this proxy for all protocols. When I like to access a https page I get the same error

- `Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca`

I also tried to to install the "little proxy" [CA certificate ](https://github.com/lightbody/browsermob-proxy#ssl-support) as recommended in the documentation but my Firefox browser (v53.03) seems to ignore it, it gets not listed after the import in the "Authorities" list. No error happens during import. 

Any suggestions or statement if this is a bug or what I can try to do?

thanks

    bin/browsermob-proxy -port 8081
    Running BrowserMob Proxy using LittleProxy implementation. To revert to the legacy implementation, run the proxy with the command-line option '--use-littleproxy false'.
    [INFO  2017-06-17T13:50:47,435 net.lightbody.bmp.proxy.Main] (main) Starting BrowserMob Proxy version 2.1.4 
    [INFO  2017-06-17T13:50:47,717 org.eclipse.jetty.util.log] (main) jetty-7.x.y-SNAPSHOT 
    [INFO  2017-06-17T13:50:47,761 org.eclipse.jetty.util.log] (main) started o.e.j.s.ServletContextHandler{/,null} 
    [INFO  2017-06-17T13:50:47,919 org.eclipse.jetty.util.log] (main) Started SelectChannelConnector@0.0.0.0:8081 
    [INFO  2017-06-17T13:51:01,977 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1894788146-19) Starting proxy at address: 0.0.0.0/0.0.0.0:8082 
    [INFO  2017-06-17T13:51:02,018 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1894788146-19) Proxy listening with TCP transport 
    [INFO  2017-06-17T13:51:02,102 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp1894788146-19) Proxy started at address: /0:0:0:0:0:0:0:0:8082 
    [ERROR 2017-06-17T13:51:49,846 org.littleshoot.proxy.impl.ClientToProxyConnection] (LittleProxy-0-ClientToProxyWorker-0) (AWAITING_INITIAL) [id: 0xa07fa514, L:/127.0.0.1:8082 - R:/127.0.0.1:52552]:  Caught an exception on ClientToProxyConnection io.netty.handler.codec.DecoderException:   javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [browsermob-dist-2.1.4.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [browsermob-dist-2.1.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
      Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_111]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_111]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[browsermob-dist-2.1.4.jar:?]
	... 15 more

    [ERROR 2017-06-17T13:51:56,467 org.littleshoot.proxy.impl.ClientToProxyConnection] (LittleProxy-0-ClientToProxyWorker-3) (AWAITING_INITIAL) [id: 0x5318510e, L:/127.0.0.1:8082 - R:/127.0.0.1:52564]: Caught an exception on ClientToProxyConnection io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [browsermob-dist-2.1.4.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [browsermob-dist-2.1.4.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [browsermob-dist-2.1.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
     Caused by: javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_111]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_111]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_111]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[browsermob-dist-2.1.4.jar:?]
	... 15 more

**Comment by egloffmark** [comment]
Ok I found the issue, it is a github-my-self-user problem  I just clicked on the link for downloading the *.cer file and chosed "save as", this saved the web page instead of the .cer file. So you need to show it as raw file. After this I could import the certificate into Firefox and the issue disappeared

**Comment by neoyagami** [comment]
Hi. 
Im having this same issue, looked for the cert in the library itself and installed it in my keychain (OSX), the errors are visible but the site can be visited
