### ISSUE TITLE
Browsermob-proxy starts requests for new proxy at 8081 even if started on a different port

### ISSUE THREAD

**Issue by sparkline-francisv** [lightbody/browsermob-proxy#663]
**browsermob-proxy (2.1.4)**

It appears that even if you start browsermob-proxy (2.1.4) on a different port (e.g. `7070`), it will still spew out a proxy starting at `8081`:
```
λ bin\browsermob-proxy.bat -port 7070
Running BrowserMob Proxy using LittleProxy implementation. To revert to the legacy implementation, run the proxy with the command-line option '--use-littleproxy false'.
[INFO  2017-07-10T10:27:59,972 net.lightbody.bmp.proxy.Main] (main) Starting BrowserMob Proxy version 2.1.4
[INFO  2017-07-10T10:28:00,027 org.eclipse.jetty.util.log] (main) jetty-7.x.y-SNAPSHOT
[INFO  2017-07-10T10:28:00,403 org.eclipse.jetty.util.log] (main) started o.e.j.s.ServletContextHandler{/,null}
[INFO  2017-07-10T10:28:00,760 org.eclipse.jetty.util.log] (main) Started SelectChannelConnector@0.0.0.0:7070
```
I have another process running on port `8081` before I executed the `curl` request.
```
λ netstat -ano | find "8081"
  TCP    0.0.0.0:8081           0.0.0.0:0              LISTENING       1128
  TCP    [::]:8081              [::]:0                 LISTENING       1128

λ curl -X POST http://localhost:7070/proxy
java.lang.RuntimeException: java.net.BindException: Address already in use: bind
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer.doStart(DefaultHttpProxyServer.java:519)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer.start(DefaultHttpProxyServer.java:463)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer.access$700(DefaultHttpProxyServer.java:70)
        at org.littleshoot.proxy.impl.DefaultHttpProxyServer$DefaultHttpProxyServerBootstrap.start(DefaultHttpProxyServer.java:799)
...
```
On the terminal where I launched browsermob-proxy, I get this message:
```
[INFO  2017-07-10T10:40:53,245 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp664186542-15) Starting proxy at address: 0.0.0.0/0.0.0.0:8081
[INFO  2017-07-10T10:40:53,278 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp664186542-15) Proxy listening with TCP transport
[WARN  2017-07-10T10:40:53,611 net.lightbody.bmp.BrowserMobProxyServer] (qtp664186542-15) Attempted to stop proxy server, but proxy was never successfully started.
```

**Comment by jekh** [comment]
When you run the REST API, the port you specify is the port the REST API is listening on, not the port that proxies will be created on. Specify the "port" parameter when you POST to /proxy in order to specify the port of the new proxy server.
