### ISSUE TITLE
Firefox: Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: InvalidArgumentError: Expected [object Undefined] undefined to be an integer

### ISSUE THREAD

**Issue by MarinaRappoport** [lightbody/browsermob-proxy#676]
There is my code:
`public class WebDriverFactory {
    public enum Drivers {
        FIREFOX, CHROME
    }
    public WebDriver getWebDriver(Drivers drivers, DesiredCapabilities capabilities) {
        WebDriver driver = null;
        switch (drivers) {
            case FIREFOX:
                System.setProperty("webdriver.gecko.driver", getClass().getClassLoader().getResource("drivers/geckodriver.exe").getFile());
                driver = new FirefoxDriver(capabilities);
                break;
            case CHROME:
                System.setProperty("webdriver.chrome.driver", getClass().getClassLoader().getResource("drivers/chromedriver.exe").getFile());
                driver = new ChromeDriver(capabilities);
                break;
        }
        return driver;
    }`

`    public static void main(String[] args) throws Exception {

        // start the proxy
        BrowserMobProxy proxy = new BrowserMobProxyServer();
        proxy.start(8080);

        // get the Selenium proxy object
        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
        // configure it as a desired capability
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

        WebDriverFactory webDriverFactory = new WebDriverFactory();
        WebDriver driver = webDriverFactory.getWebDriver(WebDriverFactory.Drivers.FIREFOX, capabilities);

        // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
        proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);

        final int[] sendStatRequest = {0};
        proxy.addRequestFilter(new RequestFilter() {
            public HttpResponse filterRequest(HttpRequest httpRequest, HttpMessageContents httpMessageContents, HttpMessageInfo httpMessageInfo) {
                if (httpMessageInfo.getOriginalUrl().matches("https://stats*progress.*")) {
                    System.out.println(httpMessageInfo.getOriginalUrl());
                    sendStatRequest[0]++;
                }
                return null;
            }
        });

        // create a new HAR with the label
        proxy.newHar("testHar.com");

        //Launch the url
        driver.get(URL);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

        // get the HAR data
        Har har = proxy.getHar();
        FileOutputStream fos = new FileOutputStream("C:\\LoadingPage\\network\\firefox.har");
        har.writeTo(fos);
        Thread.sleep(20000);
        proxy.stop();
        driver.quit();
    }`

It works absolutely fine with CHROME, but with FIREFOX I get an exception:
1500909653682	geckodriver	INFO	geckodriver 0.18.0
1500909653688	geckodriver	INFO	Listening on 127.0.0.1:20371
1500909654325	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1500909663472	Marionette	INFO	Listening on port 50000
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: InvalidArgumentError: Expected [object Undefined] undefined to be an integer
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'IDO-KABALA-10', ip: '192.168.30.131', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x44ce14 - <no info>
   4:           0x44944a - <no info>
   5:           0x4203e1 - <no info>
   6:           0x407dc7 - <no info>
   7:           0x6d95b9 - <no info>
   8:           0x4173a7 - <no info>
   9:           0x6d38b3 - <no info>
  10:     0x7ff87d022774 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
	at WebDriverFactory.getWebDriver(WebDriverFactory.java:22)
	at WebDriverCommands.main(WebDriverCommands.java:65)

**Comment by taraa62** [comment]
https://github.com/lightbody/browsermob-proxy/issues/578 ??

**Comment by happybubblefish** [comment]
I am getting the same issue. Please help, Thanks.

**Comment by Ritesh-Yadav** [comment]
There is an open issue in geckodriver which cause problem. Try following as work around:

        DesiredCapabilities capabilities = new DesiredCapabilities();
        JsonObject json = new JsonObject();
        json.addProperty("proxyType", "manual");
        json.addProperty("httpProxy", "localhost");
        json.addProperty("httpProxyPort", port);
        json.addProperty("ftpProxy", "localhost");
        json.addProperty("ftpProxyPort", port);
        json.addProperty("sslProxy", "localhost");
        json.addProperty("sslProxyPort", port);
        capabilities.setCapability(CapabilityType.PROXY, json);
        driver = new FirefoxDriver(capabilities);
