### ISSUE TITLE
Remove guava at all

### ISSUE THREAD

**Issue by filipcynarski** [lightbody/browsermob-proxy#706]
Java 8 provides everything that guava has, you can remove guava at all because it is crashing w/ Selenium guava and you need to update guava according to Selenium's releases and changes so it would be great If people don't need to struggle w/ this dependencies issues anymore.

**Comment by cafshari** [comment]
I think this is the issue I'm facing, because I'm getting the error: 

> java.lang.NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;
> 	at ...


My dependencies are:

> 	<dependency>
      <groupId>net.lightbody.bmp</groupId>
      <artifactId>browsermob-core</artifactId>
      <version>2.1.4</version>
      <scope>test</scope>
 	</dependency>


    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.3.4</version>
	</dependency>

    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>3.7.1</version>
    </dependency> 

How can I resolve this?

**Comment by mediga** [comment]
try this as an alternate solution

		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>

**Comment by cafshari** [comment]
@mediga That resulted in the following error. Any other suggestions?

> org.openqa.selenium.WebDriverException: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"40354.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'foo', ip: 'foo', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {userDataDir: /var/folders/99/tttg8hr1561...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, nativeEvents: true, platform: MAC, platformName: MAC, rotatable: false, takesHeapSnapshot: true, takesScreenshot: true, version: 62.0.3202.94, webStorageEnabled: true}
Session ID: 57a171134c4614fbcba1b564656a27d7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:324)
	at com.foo.www.analytics_testing.bmp_Selenium.test(bmp_Selenium.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by mediga** [comment]
This is most likely due to a incompatible chrome driver related issue
I see you are using chrome driver 2.9.x. 
latest is 2.33.  I think you should try the production ready driver 2.33 instead of 2.9.x

**Comment by cafshari** [comment]
@mediga adding that dependency + switching to 2.33 resolved the issue. thank you!

**Comment by avipl** [comment]
Is there any specific reason for using Guava-23-**android** can't you use Guava-23?
My library has Guava-23 which is getting conflicted with your version.

My issue is the dependency with browserMobProxy's guava-23-**android**. 
See this call 
```
waitWebDriver.until( new ExpectedCondition<WebElement>()
        {
            @Override
            public WebElement apply( WebDriver input )
            {
                return searchContext.findElement( locator.getBy() );
            }
}
```
WaitWebDriver extends FluentWait class.
The until method here is from [FluentWait](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/FluentWait.java) class, which expects an argument of type java.util.Function. The ExpectedCondtion class here which I'm passing extends Function class from Guava library(import com.google.common.base.Fuction) **which intern needs to extend java.util.Fuction**.(**Guava-23 does extends java.util.Fuction and Guava-23-android doesn't extend java.util.Fuction)**

**Comment by mediga** [comment]
I am not the developer maintaining this project, but more of freelancer who is providing guidance whereever i can based on my own experience using this product. 

I know the pain of getting stuck and no one is helping with an opensource project, so trying to help with whatever I can.

I like this product, and dont want it to die due to lack of community support. 

for your issue:

My suggestion is do this
1) clone this project to your local
2) try changing this reference  from pom.xml in the project  and rebuild. I hope that solves the problem
```
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <!-- Remove the -android when dropping support for Java 7. -->
                <version>23.0-android</version>
            </dependency>
```

There are other references in these files which I believe may not impact you, but just in case

\browsermob-proxy\browsermob-core\pom.xml
\browsermob-proxy\browsermob-rest\pom.xml

**Comment by filipcynarski** [comment]
@mediga it is workaround, and you have to maintain your fork.

Guava is not needed when you use Java1.8

**Comment by jekh** [comment]
If you're using Maven and you specify a non-android version of guava, it should automatically override the BMP dependency.

Guava does much more than provide equivalents of some of Java 8's new features, so it is not accurate to say it is "not needed when you use Java 8". In fact, BMP uses it exclusively for things that do not have Java 8 equivalents.

I do think it is time to ditch Java 7 support completely, though.

**Comment by filipcynarski** [comment]
@jekh that's true, my bad I simplified it too much. You must admit since Java 8 using guava is not as popular as before ;)

**Comment by filipcynarski** [comment]
I think issue may be closed.
