### ISSUE TITLE
Exception with example code

### ISSUE THREAD

**Issue by youchen** [lightbody/browsermob-proxy#712]
Hi Thanks for developing browsermob-proxy, pretty useful!

But I just noticed a "NoSuchFieldError" while I am trying to run the example code here
https://github.com/lightbody/browsermob-proxy/blob/master/mitm/src/test/java/net/lightbody/bmp/mitm/example/SaveGeneratedCAExample.java

```
Exception in thread "main" java.lang.NoSuchFieldError: id_tc26_signwithdigest_gost_3410_12_256
	at org.bouncycastle.operator.jcajce.OperatorHelper.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
	at net.lightbody.bmp.mitm.tools.BouncyCastleSecurityProviderTool.getCertificateSigner(BouncyCastleSecurityProviderTool.java:333)
	at net.lightbody.bmp.mitm.tools.BouncyCastleSecurityProviderTool.createCARootCertificate(BouncyCastleSecurityProviderTool.java:160)
	at net.lightbody.bmp.mitm.tools.DefaultSecurityProviderTool.createCARootCertificate(DefaultSecurityProviderTool.java:38)
	at net.lightbody.bmp.mitm.RootCertificateGenerator.generateRootCertificate(RootCertificateGenerator.java:106)
	at net.lightbody.bmp.mitm.RootCertificateGenerator.access$0(RootCertificateGenerator.java:99)
	at net.lightbody.bmp.mitm.RootCertificateGenerator$1.get(RootCertificateGenerator.java:58)
	at net.lightbody.bmp.mitm.RootCertificateGenerator$1.get(RootCertificateGenerator.java:1)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:164)
	at net.lightbody.bmp.mitm.RootCertificateGenerator.saveRootCertificateAsPemFile(RootCertificateGenerator.java:140)
	at com.iacapps.test.dlp.funnelmetric.prototype.SaveGeneratedCAExample.main(SaveGeneratedCAExample.java:21)

Process finished with exit code 1
```

**Comment by mediga** [comment]
Worked fine for me.. 

I am using 

java 1.8
windows 10
and following maven dependency
<dependency>
			<groupId>net.lightbody.bmp</groupId>
			<artifactId>browsermob-core</artifactId>
			<version>2.1.5</version>
		</dependency>

Try this also. We had another issue but similar one which got resolved by the solution here

https://github.com/lightbody/browsermob-proxy/issues/538

**Comment by gandalf7777** [comment]
Make sure that you don't have different version of bouncy castle in webapp or in you jre exertions. Its possible that you might have registered bouncy castle provider within jre. 

working fine for me with jdk7 and bc 1.59

**Comment by youchen** [comment]
Thanks @mediga @mub4799 , I'll try.
