### ISSUE TITLE
java.net.UnknownHostException when ProxyServer has a upstream proxy and visit https url

### ISSUE THREAD

**Issue by xuzheng-ayesha** [lightbody/browsermob-proxy#72]
I'm using selenium + browsermob to test a website (www.mysite.com). When visit this site, I need to use a upstream proxy ("myproxy:8080") or it will show "Server not found."

And here is my code:
@Test
public void test() throws Exception {
    ProxyServer proxyServer = new ProxyServer(5368);
    proxyServer.start();
    Map<String, String> map = new HashMap<String, String>();
    map.put("httpProxy", "myproxy:8080");
    proxyServer.setOptions(map);
		
    FirefoxProfile profile = new FirefoxProfile();
    Proxy seleniumProxy = new Proxy();
    seleniumProxy.setHttpProxy("localhost:5368");
    seleniumProxy.setSslProxy("localhost:5368");
		
    DesiredCapabilities dc = DesiredCapabilities.firefox();
    dc.setCapability(FirefoxDriver.PROFILE, profile);
    dc.setCapability(CapabilityType.PROXY, seleniumProxy);
		
    WebDriver driver = new FirefoxDriver(dc);
    // http request can work fine
    driver.get("http://www.mysite.com");
    Thread.sleep(2000);
    // cannot open https page
    driver.get("https://www.mysite.com/login.html");
    driver.quit();
		
    proxyServer.stop();
}

http requests can work fine, but when visit https url like ("https://www.mysite.com/login.html"), it will throw exception:
java.net.UnknownHostException: www.mysite.com
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:894)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1286)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1239)
	at java.net.InetAddress.getAllByName(InetAddress.java:1155)
	at java.net.InetAddress.getAllByName(InetAddress.java:1091)
	at java.net.InetAddress.getByName(InetAddress.java:1041)
	at net.lightbody.bmp.proxy.jetty.util.InetAddrPort.<init>(InetAddrPort.java:88)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handleConnect(SeleniumProxyHandler.java:455)
	at net.lightbody.bmp.proxy.BrowserMobProxyHandler.handleConnect(BrowserMobProxyHandler.java:76)
	at net.lightbody.bmp.proxy.selenium.SeleniumProxyHandler.handle(SeleniumProxyHandler.java:158)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1509)
	at net.lightbody.bmp.proxy.jetty.http.HttpContext.handle(HttpContext.java:1461)
	at net.lightbody.bmp.proxy.jetty.http.HttpServer.service(HttpServer.java:892)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.service(HttpConnection.java:815)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handleNext(HttpConnection.java:981)
	at net.lightbody.bmp.proxy.jetty.http.HttpConnection.handle(HttpConnection.java:832)
	at net.lightbody.bmp.proxy.jetty.http.SocketListener.handleConnection(SocketListener.java:245)
	at net.lightbody.bmp.proxy.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at net.lightbody.bmp.proxy.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)

Please help to have a look, thanks in advance.

**Comment by jekh** [comment]
@mediga - did you get this resolved? If you pull the latest from master, you can try setting bmp.allowNativeDnsFallback to true as described in the `Native DNS Resolution` section of the README.md.

I also noticed from the stack trace that IPv6 is enabled. Unless you really need IPv6 for your use case, you can also try setting the `java.net.preferIPv4Stack` system property to true.

**Comment by jekh** [comment]
Closing this as it is most likely resolved by PR #45.

**Comment by mediga** [comment]
Sorry about delay in responding.
I tried both the settings without success.

Any debug that can enabled to see more details?
