### ISSUE TITLE
Can't proxy using browsermob, able to proxy using mitmproxy

### ISSUE THREAD

**Issue by saurabh-agarwals** [lightbody/browsermob-proxy#752]
`[DEBUG 2018-05-18T17:43:29,797 org.eclipse.jetty.util.log] (qtp1548010882-17 - www.gstatic.com:443) REQUEST www.gstatic.com:443 on org.eclipse.jetty.server.nio.SelectChannelConnector$2@72bed59c
[DEBUG 2018-05-18T17:43:29,797 org.eclipse.jetty.util.log] (qtp1548010882-17 - www.gstatic.com:443) sessionManager=org.eclipse.jetty.server.session.HashSessionManager@30af5b6b
[DEBUG 2018-05-18T17:43:29,797 org.eclipse.jetty.util.log] (qtp1548010882-17 - www.gstatic.com:443) session=null
[DEBUG 2018-05-18T17:43:29,797 org.eclipse.jetty.util.log] (qtp1548010882-17 - www.gstatic.com:443) servlet holder=
[DEBUG 2018-05-18T17:43:29,797 org.eclipse.jetty.util.log] (qtp1548010882-17 - www.gstatic.com:443) RESPONSE www.gstatic.com:443  200
[DEBUG 2018-05-18T17:43:29,804 org.eclipse.jetty.util.log] (qtp1548010882-18) EOF org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:321) ~[browsermob-dist-2.1.4.jar:?]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214) ~[browsermob-dist-2.1.4.jar:?]
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426) ~[browsermob-dist-2.1.4.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:520) [browsermob-dist-2.1.4.jar:?]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40) [browsermob-dist-2.1.4.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528) [browsermob-dist-2.1.4.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

Any help is appreciated

**Comment by rchougule** [comment]
Hello @saurabh-agarwals ,
Were you able to solve the issue?
I am facing the same issue here. Any suggestions? 
Thanks!
