### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by jun1983** [lightbody/browsermob-proxy#755]
Hi,

I deployed BMP in standalone mode. I am running parallel testing and might create a few proxy instances in the meantime. When I posted request to create a new proxy instance, I got below error in response.

```
java.net.BindException: Address already in use
build	24-May-2018 13:33:28		at org.littleshoot.proxy.impl.DefaultHttpProxyServer.doStart(DefaultHttpProxyServer.java:555)
build	24-May-2018 13:33:28		at org.littleshoot.proxy.impl.DefaultHttpProxyServer.start(DefaultHttpProxyServer.java:499)
build	24-May-2018 13:33:28		at org.littleshoot.proxy.impl.DefaultHttpProxyServer.access$700(DefaultHttpProxyServer.java:69)
build	24-May-2018 13:33:28		at org.littleshoot.proxy.impl.DefaultHttpProxyServer$DefaultHttpProxyServerBootstrap.start(DefaultHttpProxyServer.java:877)
build	24-May-2018 13:33:28		at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:370)
build	24-May-2018 13:33:28		at net.lightbody.bmp.BrowserMobProxyServer.start(BrowserMobProxyServer.java:385)
build	24-May-2018 13:33:28		at net.lightbody.bmp.BrowserMobProxyServerLegacyAdapter.start(BrowserMobProxyServerLegacyAdapter.java:113)
build	24-May-2018 13:33:28		at net.lightbody.bmp.proxy.ProxyManager.startProxy(ProxyManager.java:247)
build	24-May-2018 13:33:28		at net.lightbody.bmp.proxy.ProxyManager.create(ProxyManager.java:200)
build	24-May-2018 13:33:28		at net.lightbody.bmp.proxy.bricks.ProxyResource.newProxy(ProxyResource.java:110)
build	24-May-2018 13:33:28		at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
build	24-May-2018 13:33:28		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build	24-May-2018 13:33:28		at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by SagarBShinde** [comment]
Hi- In case if you are still looking for resolution on this.
The port on which you are trying to start BMP proxy is already being used by some other service.
Use TCPView utility to monitor the programs running on local ports of your machine.
Try changing port and ensure it is not being used by any other program

**Comment by jun1983** [comment]
Hi Sagar, many Thanks for your reply. I understand exactly this would happen if the port is been used. Actually what I faced was  caused by this tool itself. It failed to lock the port when initiating the proxy instance. When I do more retries, it will succeed. I hope I have made my question clear. BTW, I do not see any guy keep maintain this tool. What a pity.

**Comment by SagarBShinde** [comment]
Oh got that! I am trying to use this tool to intercept the Mobile traffic from Android device and hence was going through all the threads. 
I am also facing some SSL related issues and just hoping someone would look at my issue.

**Comment by jun1983** [comment]
I workaround this problem by using try catch retry. I do not know what is your question. But JDK has a bug with closing HTTPS causing BMP crash, I would suggest  you to test this tool with latest 1.8.0.161+

**Comment by SagarBShinde** [comment]
Here is the link to my question.
https://github.com/lightbody/browsermob-proxy/issues/781

Would appreciate if you can take a look :-)
