### ISSUE TITLE
Getting encoded content from response's contents.getTextContents() from HTTPS call

### ISSUE THREAD

**Issue by hidenny** [lightbody/browsermob-proxy#772]
I was successful to install certificate to both my iPhone and Android phone. And it's okay to capture text content from HTTPS response on Android. However, on iPhone, it shows something like encoded content as below, meanwhile, the content looks good in Charles Proxy.
�d��?���+��d+�H{{���ADE/]	b# Id~H����435}ګ�^g�~T��"cUPd��q���G�W ���watr��ص��h]d����:��WX_C���*J�ҷ$��4����~�7�&���Dŧ/��+�X��Yr>Y���#���m��H
��lܼ�\�]��G�;�h�i����#��n�u����y޷YN?��z����5�ms�1X�([��-h����_���~����|��7_��}b'�n�n�y�ӿ����/=�g�����o	f���-Pݰt�`���s�po��8�����a��wAx��.�M�R��;w�}��v�vd�8��'wAV�IP�aG
��&s�x��Ƥ4�6I�/i�q҅N T�m������g�s�.`���hA��/L���
"/���E��x.�t�n=|����f�+�Z�;�����M�oNH�:{��A)�~J��A�+�$�	eތ��0$Mh���=ٔ�IV��|�a�S��@�B��|�Ѹ!�A¾K6>D(1�M�y���S���t����(��UǣM�7�D�Uss1�H4'b�Ã9p"�.l�8��y������N����Cv�1������

Any hints? Is it necessary to use setMitmManager?
Thanks all.

**Comment by selenUser** [comment]
@hidenny, can you please share you setup code for android ? when trying to catch https calls, i'm getting certificate error, see this in logcat:
event_custom_dimension15=image_load_failed}]
10-14 20:36:57.704  9732  9732 I Glide   : Root cause (1 of 1)
10-14 20:36:57.704  9732  9732 I Glide   : javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
10-14 20:36:57.704  9732  9732 I Glide   : 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:302)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:270)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
10-14 20:36:57.704  9732  9732 I Glide   : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)

Thanks for help
