### ISSUE TITLE
Tests hang on

### ISSUE THREAD

**Issue by jirfag** [lightbody/browsermob-proxy#81]
When execute ```mvn -Prelease install``` tests hang on:
```
Running net.lightbody.bmp.proxy.SslTest
INFO 08/02 20:03:13 n.l.b.p.j.h.HttpSer~ - Version Jetty/5.1.x
INFO 08/02 20:03:13 n.l.b.p.j.u.Contain~ - Started HttpContext[/,/]
INFO 08/02 20:03:13 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:13 n.l.b.p.j.u.Contain~ - Started net.lightbody.bmp.proxy.jetty.jetty.Server@1a618a48
INFO 08/02 20:03:13 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:34900
INFO 08/02 20:03:13 n.l.b.p.j.u.Threade~ - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=34900]]
INFO 08/02 20:03:13 n.l.b.p.h.BrowserMo~ - org.apache.http.NoHttpResponseException: The target server failed to respond when requesting https://www.google.ca/
INFO 08/02 20:03:13 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:34900
INFO 08/02 20:03:13 n.l.b.p.j.u.Threade~ - Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=8081]
INFO 08/02 20:03:13 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Stopped HttpContext[/,/]
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Stopped net.lightbody.bmp.proxy.jetty.jetty.Server@1a618a48
INFO 08/02 20:03:14 n.l.b.p.j.h.HttpSer~ - Version Jetty/5.1.x
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Started HttpContext[/,/]
INFO 08/02 20:03:14 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Started net.lightbody.bmp.proxy.jetty.jetty.Server@1e43329e
INFO 08/02 20:03:14 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:35721
INFO 08/02 20:03:14 n.l.b.p.j.u.Threade~ - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=35721]]
INFO 08/02 20:03:14 n.l.b.p.h.BrowserMo~ - javax.net.ssl.SSLException: Received fatal alert: unexpected_message when requesting https://www.fidelity.com/
INFO 08/02 20:03:14 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:35721
INFO 08/02 20:03:14 n.l.b.p.j.u.Threade~ - Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=8081]
INFO 08/02 20:03:14 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Stopped HttpContext[/,/]
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Stopped net.lightbody.bmp.proxy.jetty.jetty.Server@1e43329e
INFO 08/02 20:03:14 n.l.b.p.j.h.HttpSer~ - Version Jetty/5.1.x
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Started HttpContext[/,/]
INFO 08/02 20:03:14 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:14 n.l.b.p.j.u.Contain~ - Started net.lightbody.bmp.proxy.jetty.jetty.Server@3486113d
INFO 08/02 20:03:15 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:50819
INFO 08/02 20:03:15 n.l.b.p.j.u.Threade~ - Stopping Acceptor [SSL: ServerSocket[addr=0.0.0.0/0.0.0.0,localport=50819]]
INFO 08/02 20:03:15 n.l.b.p.h.BrowserMo~ - javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure when requesting https://login.salesfo$
ce.com/
INFO 08/02 20:03:15 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:50819
INFO 08/02 20:03:15 n.l.b.p.j.u.Threade~ - Stopping Acceptor ServerSocket[addr=/0.0.0.0,localport=8081]
INFO 08/02 20:03:15 n.l.b.p.j.h.SocketL~ - Stopped SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:15 n.l.b.p.j.u.Contain~ - Stopped HttpContext[/,/]
INFO 08/02 20:03:15 n.l.b.p.j.u.Contain~ - Stopped net.lightbody.bmp.proxy.jetty.jetty.Server@3486113d
INFO 08/02 20:03:15 n.l.b.p.j.h.HttpSer~ - Version Jetty/5.1.x
INFO 08/02 20:03:15 n.l.b.p.j.u.Contain~ - Started HttpContext[/,/]
INFO 08/02 20:03:15 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:8081
INFO 08/02 20:03:15 n.l.b.p.j.u.Contain~ - Started net.lightbody.bmp.proxy.jetty.jetty.Server@28d0a524
INFO 08/02 20:03:15 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:41064
INFO 08/02 20:03:16 n.l.b.p.j.h.SocketL~ - Started SocketListener on 0.0.0.0:33445
```
and i pass ```-DskipTests``` to workaround it.

**Comment by jekh** [comment]
This problem should now be fixed. When executing the request, I added an EntityUtils.consumeQuietly(...) call to consume each GET before moving onto the next one. This seems to have fixed the issue (possibly because of a single-connection pool?).

**Comment by BOPOHA** [comment]
I have the same problem with browsermob-proxy.
In my case i'm using 'modern' configuration for nginx ( https://mozilla.github.io/server-side-tls/ssl-config-generator/) with TLSv1.2 only:

```
[INFO  2016-10-03T17:51:54,322 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp762809053-16) Starting proxy at address: 0.0.0.0/0.0.0.0:8084 
[INFO  2016-10-03T17:51:54,325 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp762809053-16) Proxy listening with TCP transport 
[INFO  2016-10-03T17:51:54,326 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp762809053-16) Proxy started at address: /0:0:0:0:0:0:0:0:8084 
[INFO  2016-10-03T17:51:57,763 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-3-ProxyToServerWorker-2) (HANDSHAKING) [id: 0x7300e9fe, L:0.0.0.0/0.0.0.0:45640 ! R:itcent.net/46.28.55.105:443]: Connection to upstream server failed javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_102]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:1.8.0_102]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:1.8.0_102]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:1.8.0_102]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:1.8.0_102]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_102]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_102]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [browsermob-dist-2.1.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) [browsermob-dist-2.1.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) [browsermob-dist-2.1.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) [browsermob-dist-2.1.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

But 'intermediate' configuration for nginx:
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
```
works well.
