### ISSUE TITLE
SSL Certificate - certificate_unknown - Android

### ISSUE THREAD

**Issue by nicexavi** [lightbody/browsermob-proxy#828]
Hi, 

I'm trying to run the BrowserMobProxyServer with an Android device to monitor the traffic. 

The problem, it's that I can't monitor the traffic that runs over HTTPS. 

I've installed on my Android the [certificates](https://github.com/lightbody/browsermob-proxy/tree/master/browsermob-core/src/main/resources/sslSupport) and it still won't work. 

The BrowserMobProxyServer it's throwing me the following error: 

> `[INFO  2019-07-09T13:07:23,528 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-0-ProxyToServerWorker-5) (HANDSHAKING) [id: 0x5528a2aa, L:0.0.0.0/0.0.0.0:57932 ! R:api.fitbit.com/104.16.66.50:443]: Connection to upstream server failed javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_212]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647) ~[?:1.8.0_212]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615) ~[?:1.8.0_212]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781) ~[?:1.8.0_212]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070) ~[?:1.8.0_212]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896) ~[?:1.8.0_212]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766) ~[?:1.8.0_212]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_212]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) ~[browsermob-dist-2.1.4.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[browsermob-dist-2.1.4.jar:?]`

Can anyone help me, please?

@jekh @lightbody @nite23 ?

I'm using BrowserMobProxyServer version 2.1.5. 
I've tested with the Standalone and the embedded version. 
The error it's the same in both.

Thanks!

**Comment by nicexavi** [comment]
Really? 

Nobody?

**Comment by hunterMG** [comment]
I'm encountering this problem now. Do you know the password for the [certificate](https://github.com/lightbody/browsermob-proxy/tree/master/browsermob-core/src/main/resources/sslSupport)?

**Comment by hunterMG** [comment]
And which certificate should I use? I am working on Ubuntu 16.04 and Chrome.

**Comment by VikasNeha** [comment]
Did you ever find a solution for this issue?
