### ISSUE TITLE
contents in browsermobproxy is coming as null most of the times while doing addResponseFilter with java

### ISSUE THREAD

**Issue by arihan** [lightbody/browsermob-proxy#837]
I am using 

    'net.lightbody.bmp:browsermob-core:2.1.5'
    'org.seleniumhq.selenium:selenium-java:3.141.59'

In the below code, I am trying to override the response content . While I am using the debugging, it's going inside the if block but because contents is NULL ( 19 out of 20 times its null) , so it gives null pointer exception.
But response and messageInfo is coming fine.

     ProxyUtils.getInstance().getProxy().addResponseFilter((response, contents, messageInfo) -> {
                if (messageInfo.getOriginalUrl().contains("/getproduct")) {
                    contents.setTextContents("{\"data\":{\"items\":[]}}");
                }
            });

Exception:-

    [LittleProxy-0-ProxyToServerWorker-3] WARN 
     net.lightbody.bmp.filters.BrowserMobHttpFilterChain - Filter in 
     filter chain threw exception. Filter method may have been aborted.
    java.lang.NullPointerException

	at net.lightbody.bmp.filters.ResponseFilterAdapter.serverToProxyResponse(ResponseFilterAdapter.java:49)
	at net.lightbody.bmp.filters.BrowserMobHttpFilterChain.serverToProxyResponse(BrowserMobHttpFilterChain.java:123)
	at org.littleshoot.proxy.impl.ClientToProxyConnection.respond(ClientToProxyConnection.java:434)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.respondWith(ProxyToServerConnection.java:519)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.readHTTPInitial(ProxyToServerConnection.java:238)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.readHTTPInitial(ProxyToServerConnection.java:77)
	at org.littleshoot.proxy.impl.ProxyConnection.readHTTP(ProxyConnection.java:135)
	at org.littleshoot.proxy.impl.ProxyConnection.read(ProxyConnection.java:120)
	at org.littleshoot.proxy.impl.ProxyToServerConnection.read(ProxyToServerConnection.java:214)
	at org.littleshoot.proxy.impl.ProxyConnection.channelRead0(ProxyConnection.java:587)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$ResponseReadMonitor.channelRead(ProxyConnection.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:299)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:415)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.littleshoot.proxy.impl.ProxyConnection$BytesReadMonitor.channelRead(ProxyConnection.java:692)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1296)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1087)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:430)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at java.lang.Thread.run(Thread.java:748)

**Comment by arihan** [comment]
Though I increased the default response buffer size still its coming as null.
```proxy.addLastHttpFilterFactory(new ResponseFilterAdapter.FilterSource(new ResponseFilter() { @Override public void filterResponse(HttpResponse response, HttpMessageContents contents, HttpMessageInfo messageInfo) { if (messageInfo.getOriginalUrl().contains("abcdxyz")) { System.out.println(contents.getTextContents()); } }}, 16777216));```

**Comment by arihan** [comment]
sorted . working ok

**Comment by evgkirov** [comment]
I'm experiencing the same issue. What exactly was wrong in your case?

**Comment by arihan** [comment]
> I'm experiencing the same issue. What exactly was wrong in your case?

There are two ways you can fix it. 
1. you can set the mock at the beginning of the scenario (i.e before navigating to any url)
2. you can set the  dummy filter at the beginning
```
           browserMobProxy = new BrowserMobProxyServer();
            browserMobProxy.setTrustAllServers(true);
            browserMobProxy.start(port);
browserMobProxy.addFirstHttpFilterFactory(new ResponseFilterAdapter.FilterSource(new ResponseFilter() {
    @Override
    public void filterResponse(HttpResponse response, HttpMessageContents contents, HttpMessageInfo messageInfo) {
       
    }
}));
```
