### ISSUE TITLE
MITM with LittleProxy problem

### ISSUE THREAD

**Issue by barry-gq** [lightbody/browsermob-proxy#840]
当我使用自己的证书时，访问www.baidu.com是正常的，是可以看到自己的证书，但是当访问ip地址的时候就会报错
![image](https://user-images.githubusercontent.com/41267623/66694958-d3b80400-ecec-11e9-897f-00b5455373ab.png)
![image](https://user-images.githubusercontent.com/41267623/66694959-dd416c00-ecec-11e9-89c1-1dbb31831541.png)

**Comment by barry-gq** [comment]
Caused by: java.security.cert.CertificateException: No subject alternative names present

**Comment by barry-gq** [comment]
Caused by: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:144) ~[?:1.8.0_91]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[?:1.8.0_91]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[?:1.8.0_91]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[?:1.8.0_91]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[?:1.8.0_91]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:1.8.0_91]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496) ~[?:1.8.0_91]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_91]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_91]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:1.8.0_91]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:1.8.0_91]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:1.8.0_91]
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1324) ~[Qwa.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1232) ~[Qwa.jar:?]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1087) ~[Qwa.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1122) ~[Qwa.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491) ~[Qwa.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:430) ~[Qwa.jar:?]
	... 15 more
