### ISSUE TITLE
BrowseMob Proxy throwing error 'javax.net.ssl.SSLHandshakeException: no cipher suites in common' while using for HTTPS URLS

### ISSUE THREAD

**Issue by csharsha** [lightbody/browsermob-proxy#849]
Hi When I try to use BrowserMob Proxy REST API for HTTPS application through c# code, I am getting the following error in the BrowserMob Log. I have also installed both CA and RSA certificates along with P12 keystore certificates.

`javax.net.ssl.SSLHandshakeException: no cipher suites in common`

The REST API I used to create Proxy and Get Har are as follows.

Create Proxy
http://localhost:8080/proxy?useEcc=true&trustAllServers=true

Get Har
http://localhost:8080/proxy/8081/har?captureContent=true&captureBinaryContent=true&captureHeaders=true

Log
`2020-03-13T19:06:19,032 org.littleshoot.proxy.impl.ProxyToServerConnection] (LittleProxy-0-ProxyToServerWorker-2) (HANDSHAKING)
 at sun.security.ssl.Handshaker.checkThrown(Unknown Source) ~[?:1.7.0_45]
 at sun.security.ssl.SSLEngineImpl.checkTaskThrown(Unknown Source) ~[?:1.7.0_45]
 at sun.security.ssl.SSLEngineImpl.readNetRecord(Unknown Source) ~[?:1.7.0_45]
 at sun.security.ssl.SSLEngineImpl.unwrap(Unknown Source) ~[?:1.7.0_45]
 at javax.net.ssl.SSLEngine.unwrap(Unknown Source) ~[?:1.7.0_45]
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) ~[browsermob-dist-
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[browsermob-dist-
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) ~[browsermob-dist-2.
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[browsermob-dist-2.1.4.j
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) ~[browsermob-dist-
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[browsermob-dist-
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[browsermob-dist-2.1.4.jar
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) ~[browsermob-dist-2.1.4.jar:?]
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [browsermob-dist-2.1.4.jar:?]
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [browsermob-dist-2.1.4.jar:?]`

Can anyone help!

Thanks

**Comment by csharsha** [comment]
Sorry this issue was solved when I used 

http://localhost:8080/proxy?trustAllServers=true

only during creation of new proxy.

Thanks
